(function() {
  const K = window.SC3, D = window.SC3_DATA, M = window.SC3_MONEY;
  const fmt = M.fmt;
  const { cx, Icon, Badge, Button, Card, List, ListRow, ThemeProvider, AppRoot, Mark, Product, VTracker, DocCard, Money } = K;
  const q = new URLSearchParams(location.search);
  const OPT = q.get("opt") || "a", VIEW = q.get("view") || "paper", BANK = q.get("bank") || "fi";
  const batch = D.BATCHES.find((b) => b.id === "MF-2410-118"), sku = D.SKUS[batch.sku], dist = D.DISTRIBUTORS[batch.distributor];
  const n = D.MANGO_FB, DN = D.JOURNEY.donation, C = D.CLIENT;
  const wo = M.writeOff(n, sku);
  const meals = D.MANGO_PLAN.meals;
  const bb = fmt.date(batch.bestBefore);
  const BANKS = {
    fi: {
      name: "Feeding India",
      kind: "In-app receipt",
      title: "Donation receipt",
      stamp: "RECEIVED",
      no: "FI/HYD/26-27/0417",
      by: "Meera, city lead",
      at: `${DN.date}, ${DN.time}`,
      where: `${dist.godown}, ${dist.city}`,
      to: DN.spot,
      note: `Issued in the app by Feeding India when the packs were collected. Munchly's evidence for BRSR Principle 6; not a tax certificate. The FSSAI surplus-food checklist travels with it.`
    },
    ifbn: {
      name: "India FoodBanking Network",
      kind: "Donation acknowledgement (CSR / 80G, indicative)",
      title: "Donation acknowledgement",
      stamp: "ACKNOWLEDGED",
      no: "IFBN/ACK/26-27/0112",
      by: "Warehouse lead, Hyderabad",
      at: `${DN.date}, ${DN.time}`,
      where: `${dist.godown}, ${dist.city}`,
      to: "the member warehouse, Hyderabad",
      note: "An acknowledgement for the donor's CSR records (indicative). Section 80G applies to gifts of money, so this is not a tax certificate."
    }
  };
  const B = BANKS[BANK];
  const Line = ({ k, v, strong, sub }) => /* @__PURE__ */ React.createElement("div", { className: "pp-line" }, /* @__PURE__ */ React.createElement("span", null, k, sub && /* @__PURE__ */ React.createElement("em", null, " ", sub)), /* @__PURE__ */ React.createElement("span", { className: strong ? "pp-strong" : "" }, v));
  const head = (title, no, right) => /* @__PURE__ */ React.createElement("div", { className: "pp-head" }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { className: "pp-title" }, title), /* @__PURE__ */ React.createElement("div", { className: "pp-no" }, no)), right);
  function Receipt({ b = B, inner }) {
    const body = /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", { className: "pp-parties" }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("em", null, "Donor"), /* @__PURE__ */ React.createElement("b", null, C.name), /* @__PURE__ */ React.createElement("span", null, "through ", dist.name, ", ", b.where), /* @__PURE__ */ React.createElement("span", { className: "pp-mono" }, "FSSAI ", C.fssai)), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("em", null, "Received by"), /* @__PURE__ */ React.createElement("b", null, b.name), /* @__PURE__ */ React.createElement("span", null, dist.city, BANK === "ifbn" && b === BANKS.ifbn ? " · illustrative" : ""), /* @__PURE__ */ React.createElement("span", { className: "pp-mono" }, b.kind))), /* @__PURE__ */ React.createElement("table", { className: "pp-table" }, /* @__PURE__ */ React.createElement("thead", null, /* @__PURE__ */ React.createElement("tr", null, /* @__PURE__ */ React.createElement("th", null, "Goods"), /* @__PURE__ */ React.createElement("th", null, "Packs"), /* @__PURE__ */ React.createElement("th", null, "Weight"))), /* @__PURE__ */ React.createElement("tbody", null, /* @__PURE__ */ React.createElement("tr", null, /* @__PURE__ */ React.createElement("td", null, sku.name, /* @__PURE__ */ React.createElement("br", null), /* @__PURE__ */ React.createElement("em", null, "Batch ", batch.id, " · best before ", bb)), /* @__PURE__ */ React.createElement("td", null, fmt.num(n)), /* @__PURE__ */ React.createElement("td", null, fmt.kg(wo.kg))))), /* @__PURE__ */ React.createElement(Line, { k: "Collected", sub: b.by, v: b.at }), /* @__PURE__ */ React.createElement(Line, { k: "Served at", v: b.to }), /* @__PURE__ */ React.createElement(Line, { k: "Meals", sub: "a pack a meal, indicative", v: fmt.num(meals) }), b === BANKS.ifbn && /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", { className: "pp-sub" }, "For the donor's CSR records"), /* @__PURE__ */ React.createElement(Line, { k: "Value at Munchly's cost", sub: `${fmt.num(n)} × ₹${sku.cost}, indicative`, v: fmt.inr2(wo.stock) }), /* @__PURE__ */ React.createElement(Line, { k: "CSR activity", v: "Schedule VII (i), hunger" })), /* @__PURE__ */ React.createElement("p", { className: "pp-note" }, b.note));
    if (inner) return body;
    return /* @__PURE__ */ React.createElement("div", { className: "paper pp" }, head(b.title, `${b.no} · ${b.kind === "In-app receipt" ? "in-app" : "acknowledgement"} · ${DN.date}`, /* @__PURE__ */ React.createElement("span", { className: "pp-stamp ok" }, b.stamp)), body);
  }
  const CHECKS = ["Sealed, undamaged packs", `Best before ${bb}, 18 days left`, "Ambient storage, away from sunlight", `Batch ${batch.id} on every carton`, `Donor: ${C.short} via ${dist.name}`];
  function Handover({ received = true }) {
    return /* @__PURE__ */ React.createElement("div", { className: "paper pp" }, head("Surplus-food handover", `${received ? B.no : "awaiting collection"} · ${C.short} → ${B.name}`, /* @__PURE__ */ React.createElement("span", { className: cx("pp-stamp", received && "ok") }, received ? B.stamp : "BOOKED")), /* @__PURE__ */ React.createElement("div", { className: "pp-sub" }, "The donor's FSSAI checklist"), CHECKS.map((c) => /* @__PURE__ */ React.createElement("div", { key: c, className: "pp-line" }, /* @__PURE__ */ React.createElement("span", { className: "row tight" }, /* @__PURE__ */ React.createElement(Icon, { name: "square-check", size: 14 }), c), /* @__PURE__ */ React.createElement("span", null))), /* @__PURE__ */ React.createElement("div", { className: "pp-sub" }, received ? `${B.name}'s ${B.kind === "In-app receipt" ? "receipt" : "acknowledgement"}` : `${B.name} signs here on collection`), received ? /* @__PURE__ */ React.createElement(Receipt, { inner: true }) : /* @__PURE__ */ React.createElement("p", { className: "pp-note" }, "The bottom half fills in when ", B.name, " marks the packs collected."));
  }
  const tracker = /* @__PURE__ */ React.createElement(VTracker, { items: [{ id: "req", title: "Requested by the donation agent", time: DN.asked }, { id: "conf", title: "Confirmed by Meera", time: DN.confirmed }, { id: "col", title: `Collected from ${DN.from}`, time: DN.collected }, { id: "srv", title: `Served at ${DN.spot}`, time: "this week" }], current: 3, done: 3 });
  function PickupCard() {
    return /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "Pickup"), /* @__PURE__ */ React.createElement(Badge, { tone: "green", icon: "check" }, "collected")), tracker, OPT === "a" && /* @__PURE__ */ React.createElement("button", { type: "button", className: "row interactive", style: { gap: 12, padding: "12px 14px", borderRadius: 14, background: "var(--primary-soft)", border: 0, textAlign: "left", color: "inherit", font: "inherit", width: "100%", cursor: "pointer" } }, /* @__PURE__ */ React.createElement(Icon, { name: "receipt", size: 20 }), /* @__PURE__ */ React.createElement("span", { className: "grow" }, /* @__PURE__ */ React.createElement("b", null, B.title, " ", B.no), /* @__PURE__ */ React.createElement("div", { className: "t-footnote" }, fmt.num(n), " drinks served · shared with ", C.short, " for its BRSR table")), /* @__PURE__ */ React.createElement("span", { className: "row tight t-subhead strong", style: { color: "var(--primary-text)" } }, "View", /* @__PURE__ */ React.createElement(Icon, { name: "chevron-right", size: 16 }))), OPT === "b" && /* @__PURE__ */ React.createElement("div", { className: "row", style: { gap: 12, padding: "12px 14px", borderRadius: 14, background: "var(--primary-soft)" } }, /* @__PURE__ */ React.createElement(Icon, { name: "clipboard-check", size: 20 }), /* @__PURE__ */ React.createElement("span", { className: "grow" }, /* @__PURE__ */ React.createElement("b", null, "Handover signed · ", B.no), /* @__PURE__ */ React.createElement("div", { className: "t-footnote" }, "Your receipt is on the handover beside: ", fmt.num(n), " drinks served"))), OPT === "c" && /* @__PURE__ */ React.createElement("div", { className: "row", style: { gap: 12, padding: "12px 14px", borderRadius: 14, background: "var(--primary-soft)" } }, /* @__PURE__ */ React.createElement(Icon, { name: "receipt", size: 20 }), /* @__PURE__ */ React.createElement("span", { className: "grow" }, /* @__PURE__ */ React.createElement("b", null, "Receipt ", B.no, " in your register"), /* @__PURE__ */ React.createElement("div", { className: "t-footnote" }, fmt.num(n), " drinks served · shared with ", C.short, " for its BRSR table"))));
  }
  const REGISTER = [
    { no: B.no, date: DN.date, brand: C.short, batch: batch.id, goods: sku.name, packs: n, real: true },
    { no: "FI/HYD/26-27/0398", date: "Wed 30 Sep", brand: "Another brand", batch: "illustrative", goods: "Biscuits 200 g", packs: 120 },
    { no: "FI/HYD/26-27/0371", date: "Mon 21 Sep", brand: "Another brand", batch: "illustrative", goods: "Instant oats 500 g", packs: 64 }
  ];
  function Register({ desk }) {
    return /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "card-title" }, desk ? "Donation receipts" : "Your receipts"), /* @__PURE__ */ React.createElement(Badge, null, desk ? "this quarter" : `${REGISTER.length} this month`)), /* @__PURE__ */ React.createElement(List, null, REGISTER.map((r) => /* @__PURE__ */ React.createElement(ListRow, { key: r.no, title: desk ? `${r.date} · ${B.name}` : `${r.date} · ${r.brand}`, sub: `${r.goods} · ${r.batch} · ${r.no}`, value: /* @__PURE__ */ React.createElement("span", { className: "row tight" }, /* @__PURE__ */ React.createElement("span", { className: "tnum strong" }, fmt.num(r.packs)), /* @__PURE__ */ React.createElement(Icon, { name: "chevron-right", size: 16 })) }))), desk && /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, "The receipts behind the quarter's donated kilos, each with its PDF. Two rows are illustrative; the Mango Drink's is the story's."));
  }
  function Meera() {
    const app = K.useApp();
    const phone = app.bp === "phone";
    const side = OPT === "b" ? /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 10 } }, /* @__PURE__ */ React.createElement("span", { className: "t-headline" }, "Surplus-food handover"), /* @__PURE__ */ React.createElement(Handover, null)) : /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 10 } }, /* @__PURE__ */ React.createElement("span", { className: "t-headline" }, "FSSAI surplus-food checklist"), /* @__PURE__ */ React.createElement(Card, { className: "paper stack tight", style: { padding: 18 } }, CHECKS.map((c) => /* @__PURE__ */ React.createElement("span", { key: c, className: "row tight t-subhead" }, /* @__PURE__ */ React.createElement(Icon, { name: "square-check", size: 16 }), c))));
    return /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 18 } }, /* @__PURE__ */ React.createElement("div", { className: "stack tight", style: { gap: 2 } }, /* @__PURE__ */ React.createElement("span", { className: "t-caption subtle" }, "Meera · ", B.name === "Feeding India" ? "Feeding India" : B.name, " · Pickups"), /* @__PURE__ */ React.createElement("span", { className: "t-title1", style: { fontFamily: "var(--font-display)", fontWeight: 760 } }, "Pickups")), /* @__PURE__ */ React.createElement("div", { className: cx("s110-cols", phone && "one") }, /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 16 } }, /* @__PURE__ */ React.createElement(Card, { className: "row", style: { gap: 16, padding: 20 } }, /* @__PURE__ */ React.createElement(Product, { name: "pack-mango", size: phone ? 72 : 92, float: true }), /* @__PURE__ */ React.createElement("div", { className: "stack tight", style: { gap: 4 } }, /* @__PURE__ */ React.createElement("div", { className: "t-title2" }, fmt.num(n), " packs of Mango Drink"), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, dist.name, " · ", DN.from, " · ", DN.date))), /* @__PURE__ */ React.createElement(PickupCard, null), OPT === "c" && /* @__PURE__ */ React.createElement(Register, null)), side));
  }
  function Opened() {
    return /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 12 } }, /* @__PURE__ */ React.createElement("div", { className: "row between" }, /* @__PURE__ */ React.createElement("span", { className: "t-headline" }, B.title), /* @__PURE__ */ React.createElement(Button, { variant: "secondary", size: "sm", icon: "download" }, "PDF")), OPT === "b" ? /* @__PURE__ */ React.createElement(Handover, null) : /* @__PURE__ */ React.createElement(Receipt, null), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, OPT === "c" ? "Opened from your register; Munchly reads the same receipt in its donation register." : `The same paper is in ${C.short}' document pack for ${batch.id}.`));
  }
  const PACK = [
    { id: "support", type: "Price-support credit note", no: "CN/0118", owner: C.short, status: "generated", amount: 6338 },
    { id: "itc", type: "GST ITC memo", no: "s.17(5)(h)", owner: C.short, status: "generated", amount: 837 }
  ];
  function Desk() {
    if (OPT === "c") return /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 18 } }, /* @__PURE__ */ React.createElement("div", { className: "stack tight", style: { gap: 2 } }, /* @__PURE__ */ React.createElement("span", { className: "t-caption subtle" }, "Vikram · Finance & ESG · Quarter"), /* @__PURE__ */ React.createElement("span", { className: "t-title1", style: { fontFamily: "var(--font-display)", fontWeight: 760 } }, "Finance & ESG")), /* @__PURE__ */ React.createElement("div", { className: "s110-cols" }, /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 16 } }, /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "BRSR Core"), /* @__PURE__ */ React.createElement(Button, { variant: "secondary", size: "sm", icon: "download" }, "Export BRSR table")), /* @__PURE__ */ React.createElement("span", { className: "t-footnote" }, "Food waste: packaged food past quick-commerce gates · donated kilos evidenced by the food banks' receipts below.")), /* @__PURE__ */ React.createElement(Register, { desk: true })), /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 10 } }, /* @__PURE__ */ React.createElement("span", { className: "t-headline" }, B.title, " · ", B.no), /* @__PURE__ */ React.createElement(Receipt, null))));
    const docs = OPT === "a" ? [...PACK, { id: "fssai", type: "FSSAI surplus-food checklist", no: `${n} units`, owner: C.short, status: "generated" }, { id: "receipt", type: B.title, no: B.no, owner: B.name, status: "generated", note: `${fmt.num(n)} packs received · ${fmt.num(meals)} meals` }, { id: "destruction", type: "Destruction certificate", no: "0 units left", owner: C.short, status: "not required" }] : [...PACK, { id: "fssai", type: "Surplus-food handover", no: B.no, owner: `${C.short} → ${B.name}`, status: "generated", note: `${fmt.num(n)} packs received` }, { id: "destruction", type: "Destruction certificate", no: "0 units left", owner: C.short, status: "not required" }];
    return /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 18 } }, /* @__PURE__ */ React.createElement("div", { className: "stack tight", style: { gap: 2 } }, /* @__PURE__ */ React.createElement("span", { className: "t-caption subtle" }, "Anita · Paperwork · ", batch.id), /* @__PURE__ */ React.createElement("span", { className: "t-title1", style: { fontFamily: "var(--font-display)", fontWeight: 760 } }, "Paperwork"), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, batch.id, " · prepared by the Paperwork agent once every line was done")), /* @__PURE__ */ React.createElement("div", { className: "s110-cols" }, /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 12 } }, /* @__PURE__ */ React.createElement("span", { className: "t-headline" }, "Document pack"), /* @__PURE__ */ React.createElement("div", { className: "docgrid" }, docs.map((d) => /* @__PURE__ */ React.createElement("div", { key: d.id, className: cx("docpick", (d.id === "receipt" || OPT === "b" && d.id === "fssai") && "on") }, /* @__PURE__ */ React.createElement(DocCard, { doc: d, onOpen: () => {
    } })))), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, "Evidence for the BRSR line: 52 kirana order logs · CN/0118 · ", OPT === "a" ? `FSSAI checklist · ${B.no}` : `handover ${B.no}`)), /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 10 } }, /* @__PURE__ */ React.createElement("span", { className: "t-headline" }, OPT === "a" ? B.title : "Surplus-food handover"), /* @__PURE__ */ React.createElement("span", { className: "t-footnote subtle" }, "Issued by ", B.name), OPT === "a" ? /* @__PURE__ */ React.createElement(Receipt, null) : /* @__PURE__ */ React.createElement(Handover, null))));
  }
  function Page() {
    const view = { paper: () => /* @__PURE__ */ React.createElement("div", { style: { maxWidth: 560 } }, OPT === "b" ? /* @__PURE__ */ React.createElement(Handover, null) : /* @__PURE__ */ React.createElement(Receipt, null)), meera: Meera, open: Opened, desk: Desk }[VIEW] || Meera;
    return /* @__PURE__ */ React.createElement("div", { className: cx("s110", "v-" + VIEW) }, view());
  }
  ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(ThemeProvider, null, /* @__PURE__ */ React.createElement(AppRoot, { scroll: "window" }, /* @__PURE__ */ React.createElement(Page, null))));
})();
