(function() {
  const { useState } = React;
  const K = window.SC3, D = window.SC3_DATA, M = window.SC3_MONEY, S = window.SC3_SCREENS, F = window.SCF;
  const { Card, Money, Button, Sheet, Product } = K;
  const fmt = M.fmt;
  function Table({ b, page }) {
    return /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 14 } }, /* @__PURE__ */ React.createElement("p", { className: "t-subhead", style: { margin: 0 } }, "What you sold plus what ", D.WORKSPACE.short, " credited you is what each batch cost you, so you end whole on every one."), /* @__PURE__ */ React.createElement("div", { className: "fx-table", role: "table", "aria-label": "How your cleared batches add up" }, /* @__PURE__ */ React.createElement("div", { className: "fx-tr head", role: "row" }, /* @__PURE__ */ React.createElement("span", { role: "columnheader" }, "Batch"), /* @__PURE__ */ React.createElement("span", { role: "columnheader" }, "Cost you"), /* @__PURE__ */ React.createElement("span", { role: "columnheader", className: page === "orders" ? "here" : void 0 }, "Sold"), /* @__PURE__ */ React.createElement("span", { role: "columnheader", className: page === "batches" ? "here" : void 0 }, "Credited"), /* @__PURE__ */ React.createElement("span", { role: "columnheader" }, "You end")), b.sums.map((x) => {
      const sku = x.sku.img ? x.sku : D.SKUS[x.sku];
      return /* @__PURE__ */ React.createElement("div", { className: "fx-tr", role: "row", key: x.ref }, /* @__PURE__ */ React.createElement("span", { role: "cell", className: "row tight", style: { gap: 8 } }, /* @__PURE__ */ React.createElement(Product, { name: sku.img, size: 28, alt: "" }), /* @__PURE__ */ React.createElement("span", { className: "stack", style: { gap: 0 } }, /* @__PURE__ */ React.createElement("b", null, sku.name), /* @__PURE__ */ React.createElement("span", { className: "mono t-caption subtle" }, x.ref))), /* @__PURE__ */ React.createElement("span", { role: "cell", className: "tnum" }, fmt.inr(x.cost)), /* @__PURE__ */ React.createElement("span", { role: "cell", className: "tnum" }, fmt.inr(x.sold)), /* @__PURE__ */ React.createElement("span", { role: "cell", className: "tnum" }, fmt.inr(x.credit)), /* @__PURE__ */ React.createElement("span", { role: "cell", className: "tnum" }, fmt.inr(x.gain)));
    }), /* @__PURE__ */ React.createElement("div", { className: "fx-tr total", role: "row" }, /* @__PURE__ */ React.createElement("span", { role: "cell" }, /* @__PURE__ */ React.createElement("b", null, b.n, " batches")), /* @__PURE__ */ React.createElement("span", { role: "cell", className: "tnum" }, fmt.inr(b.cost)), /* @__PURE__ */ React.createElement("span", { role: "cell", className: "tnum" }, fmt.inr(b.sold)), /* @__PURE__ */ React.createElement("span", { role: "cell", className: "tnum" }, fmt.inr(b.credit)), /* @__PURE__ */ React.createElement("span", { role: "cell", className: "tnum" }, "₹0"))), /* @__PURE__ */ React.createElement("p", { className: "t-footnote muted", style: { margin: 0 } }, "Sold is on Orders, every order on its paper; credited is on Batches, ", b.notes, " credit notes in the batches' papers. Each batch's Money tab shows its own lines."));
  }
  function Head({ b, page, live }) {
    const [open, setOpen] = useState(false);
    const W = D.WORKSPACE.short;
    const v = page === "batches" ? b.credit : b.sold + (live || 0);
    return /* @__PURE__ */ React.createElement(Card, { className: "stack", style: { gap: 10 } }, /* @__PURE__ */ React.createElement("div", { className: "lg-fig" }, /* @__PURE__ */ React.createElement(Money, { value: v, size: "l" }), /* @__PURE__ */ React.createElement("span", { className: "lg-what" }, page === "batches" ? `credited by ${W} since July` : `sold from ${W}'s batches since ${D.WORKSPACE.since}`)), /* @__PURE__ */ React.createElement("p", { className: "lg-working" }, page === "batches" ? `The price support and the expiry credit on ${b.n} batches cleared at your godown: ${b.notes} credit notes, each in its batch's papers.` : `From the kiranas' schemes, the ExpireSoon lots and the staff sales of ${W}'s batches.`), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement(Button, { variant: "secondary", size: "sm", icon: "coins", onClick: () => setOpen(true) }, "How this adds up")), /* @__PURE__ */ React.createElement(Sheet, { open, onClose: () => setOpen(false), title: "How your batches add up" }, /* @__PURE__ */ React.createElement(Table, { b, page })));
  }
  const RowValue = ({ x }) => /* @__PURE__ */ React.createElement("span", { className: "lg-val" }, /* @__PURE__ */ React.createElement("b", { className: "tnum" }, fmt.inr(x.credit)), /* @__PURE__ */ React.createElement("em", null, "credited"));
  const BatchValue = ({ sold }) => /* @__PURE__ */ React.createElement("span", { className: "tnum strong" }, fmt.inr(sold));
  Object.assign(S, {
    DistBatches: (props) => /* @__PURE__ */ React.createElement(F.DistBatchesPage, { ...props, Head, RowValue }),
    DistOrders: (props) => /* @__PURE__ */ React.createElement(F.DistOrdersPage, { ...props, Head, BatchValue })
  });
})();
