// Smart-Clearance app v2 · mock of Cloud Pub/Sub plus the agents on Cloud Run that subscribe to it.
// Bus.publish(topic, payload) logs the event and lets the agents react on timers, writing to the store and notifying people.
(function () {
  const subs = {}; const timers = [];
  const later = (fn, ms) => { const t = setTimeout(fn, ms); timers.push(t); return t; };
  const DB = () => window.DB;
  const hhmm = () => new Date().toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", hour12: false });
  const usersIn = (role, org) => DB().list("users", { where: Object.assign({ role, status: "active" }, org ? { org } : {}) });
  const notifyRole = (role, n, org) => usersIn(role, org).forEach(u => DB().notify(u.id, n));
  const PLAN = { shops: { packets: 588, cartons: "24½", price: 18, gross: 10584, shopsCount: 14 }, online: { packets: 772, cartons: "32 + 4", price: 15, floor: 14, gross: 11580 }, costs: 394, net: 21770, pctMrp: 54, bin: 27717, swing: 49487, itc: 2611 };

  const Bus = {
    publish(topic, payload) { const ev = DB().insert("events", { topic, payload: payload || {}, at: new Date().toISOString() }); (subs[topic] || []).forEach(fn => { try { fn(payload || {}, ev); } catch (e) { console.error(e); } }); (subs["*"] || []).forEach(fn => fn(topic, payload || {}, ev)); return ev; },
    subscribe(topic, fn) { (subs[topic] = subs[topic] || []).push(fn); return () => { subs[topic] = subs[topic].filter(f => f !== fn); }; },
    cancelAll() { timers.forEach(clearTimeout); timers.length = 0; },
    topics: ["watcher.run", "batch.flagged", "photo.requested", "photo.verified", "plan.ready", "plan.approved", "plan.rejected", "listing.posted", "offer.pushed", "order.placed", "bid.placed", "bid.countered", "bid.accepted", "shipment.started", "shipment.dispatched", "documents.ready", "ledger.closed", "user.invited", "rule.changed"],
    PLAN,
  };

  // ---- the agents (each is a subscriber; the real ones run on Cloud Run with the same topics) ----
  // Watcher: a manual run re-checks every batch against the gates and sell-through.
  Bus.subscribe("watcher.run", () => { const rules = DB().rules(); let flagged = 0; DB().all("batches").forEach(b => { if (!["watching", "at_risk"].includes(b.status)) return; const p = DB().product(b.product); const need = Math.max(rules.gates.blinkit, Math.round(p.life * rules.gates.zepto)); const willSell = b.sellPerDay * Math.max(0, b.daysLeft - 7); const risk = b.daysLeft < need && willSell < b.packets; if (risk && b.status !== "at_risk") { flagged++; DB().update("batches", b.id, { status: "at_risk", atRisk: b.packets - willSell, binCost: Math.round(b.cartons * p.perCarton * p.cost * 1.27) }); Bus.publish("batch.flagged", { batch: b.id }); } }); DB().audit("system", "watcher run", DB().all("batches").length + " batches · " + flagged + " newly flagged", "cloud-run"); });
  Bus.subscribe("batch.flagged", ({ batch }) => { const b = DB().get("batches", batch); const p = DB().product(b.product); notifyRole("operator", { title: p.name + " · " + (DB().org(b.org) || {}).city, body: Math.round(b.atRisk || 0).toLocaleString("en-IN") + " packets will not sell before " + b.bestBefore + ". The apps have stopped taking the batch.", link: "batches/" + b.id }); });
  // Vision: a photo request goes to the distributor; a sent photo is read and verified.
  Bus.subscribe("photo.requested", ({ batch, by }) => { const b = DB().get("batches", batch); const p = DB().product(b.product); DB().update("batches", batch, { photo: { status: "requested", at: new Date().toISOString(), by }, status: b.status === "watching" ? "at_risk" : b.status }); notifyRole("distributor", { title: "Ek photo chahiye", body: p.name + ", batch " + batch + ", carton ka label. Bas ek.", hindi: true, link: "photos/" + batch }, b.org); });
  Bus.subscribe("photo.sent", ({ batch }) => { DB().update("batches", batch, { photo: { status: "reading", at: new Date().toISOString() } }); later(() => { DB().update("batches", batch, { photo: { status: "verified", at: new Date().toISOString(), confidence: 0.97 }, status: "verifying" }); Bus.publish("photo.verified", { batch }); }, 1500); });
  // Valuer + Router: a verified label yields six priced doors and a split, waiting for approval.
  Bus.subscribe("photo.verified", ({ batch }) => { later(() => { const b = DB().get("batches", batch); const plan = DB().insert("plans", { batch, status: "awaiting_approval", doors: [{ id: "shops", net: 420, pick: true }, { id: "online", net: 360, pick: true }, { id: "d2c", net: 288 }, { id: "staff", net: 288 }, { id: "bank", net: -12 }, { id: "bin", net: -489 }], split: PLAN, net: PLAN.net, bin: PLAN.bin, itc: PLAN.itc, at: new Date().toISOString() }); DB().update("batches", batch, { status: "planned", plan: plan.id }); Bus.publish("plan.ready", { batch, plan: plan.id }); const p = DB().product(b.product); notifyRole("operator", { title: "Plan ready for " + batch, body: "24½ cartons to shops at ₹18, 32 cartons online at ₹15. You get ₹21,770 instead of losing ₹27,717. Tap to review.", link: "batches/" + batch + "/plan" }); }, 1200); });
  // Approval releases the Lister and Outreach; orders trickle in.
  Bus.subscribe("plan.approved", ({ batch, plan, by }) => { DB().update("plans", plan, { status: "approved", approvedBy: by, approvedAt: new Date().toISOString() }); DB().update("batches", batch, { status: "approved" }); DB().audit(by, "approved plan", batch); later(() => { const l = DB().insert("listings", { id: "ES-" + (88200 + Math.floor(Math.random() * 90)), batch, marketplace: "ExpireSoon", qty: 772, price: 15, floor: 14, status: "live", at: new Date().toISOString() }); DB().update("batches", batch, { status: "executing", listing: l.id }); Bus.publish("listing.posted", { batch, listing: l.id }); const offer = DB().insert("offers", { batch, cluster: "Nagpur East", packets: 588, price: 18, scheme: "10 + 2", windowHours: 48, status: "live", textHindi: "आज का ऑफर: Munchly Masala Chips 150 g, 10 पैकेट लो, 2 मुफ़्त. सिर्फ़ 48 घंटे.", at: new Date().toISOString(), shopsNotified: 38 }); Bus.publish("offer.pushed", { batch, offer: offer.id }); notifyRole("retailer", { title: "आज का ऑफर", body: offer.textHindi, hindi: true, link: "offers/" + offer.id }); notifyRole("distributor", { title: "Van route for Tuesday updated", body: "14 drops, 24½ cartons. Hyderabad lot ships when the buyer's balance lands.", link: "rounds" }, DB().get("batches", batch).org); const round = DB().insert("shipments", { id: "round-" + Date.now().toString(36), kind: "van", org: DB().get("batches", batch).org, batch, label: "Tuesday round · Nagpur East", stops: 14, done: 0, status: "planned", at: new Date().toISOString() }); let n = 0; const tick = () => { if (n >= 14) return; const shop = DB().all("shops")[n]; DB().insert("orders", { type: "shop", batch, party: shop.name + " · " + shop.area, shop: shop.id, qty: shop.typicalQty, price: 18, status: "confirmed", at: new Date().toISOString(), org: "o-rakesh", offer: offer.id }); Bus.publish("order.placed", { batch, shop: shop.id, qty: shop.typicalQty }); n++; later(tick, 650 + Math.random() * 500); }; later(tick, 900); }, 1000); });
  Bus.subscribe("plan.rejected", ({ batch, plan, by, reason }) => { DB().update("plans", plan, { status: "rejected", rejectedBy: by, reason }); DB().update("batches", batch, { status: "at_risk" }); DB().audit(by, "rejected plan", batch + (reason ? " · " + reason : "")); });
  // Negotiator counters anything under the floor.
  Bus.subscribe("bid.placed", ({ listing, bid }) => { const l = DB().get("listings", listing); later(() => { const b = DB().get("bids", bid); if (!b) return; if (b.price >= l.floor + 0.2) { DB().update("bids", bid, { status: "accepted" }); Bus.publish("bid.accepted", { listing, bid, price: b.price }); } else { DB().update("bids", bid, { status: "countered", counter: Math.max(l.floor + 0.2, Math.round((b.price + 1.2) * 10) / 10) }); Bus.publish("bid.countered", { listing, bid }); } }, 1500); });
  Bus.subscribe("bid.accepted", ({ listing, bid, price }) => { const l = DB().get("listings", listing); const b = DB().get("bids", bid); const final = price || b.counter || b.price; DB().update("listings", listing, { status: "awarded", awardedTo: b.by, awardedPrice: final }); const gross = Math.round(l.qty * final); DB().insert("orders", { type: "online", batch: l.batch, party: (DB().org(b.by) || {}).name || b.by, qty: l.qty, price: final, status: "token_paid", token: Math.round(gross * 0.15), balance: gross - Math.round(gross * 0.15), at: new Date().toISOString(), org: b.by }); notifyRole("operator", { title: "Awarded · ExpireSoon", body: l.qty + " packets at ₹" + final.toFixed(2) + ". Token received; balance before dispatch.", link: "batches/" + l.batch + "/execution" }); });
  // Shipments close the loop: documents, then the ledger.
  Bus.subscribe("shipment.dispatched", ({ batch, by }) => { DB().update("batches", batch, { status: "settling" }); DB().audit(by, "dispatched", batch); notifyRole("finance", { title: "Stock moved · " + batch, body: "Cartons delivered to shops and on the truck. The document pack is ready to prepare.", link: "documents" }); });
  Bus.subscribe("documents.ready", ({ batch, by }) => { const docs = [["INV/26-27/" + (900 + Math.floor(Math.random() * 90)), "invoice", "Tax invoice", 12277, "issued"], ["CN/" + (100 + Math.floor(Math.random() * 50)), "credit_note", "Credit note", 1568, "issued"], ["EWB/" + batch.slice(-3), "eway", "E-way bill check", 0, "not_required"], ["ITC/" + batch.slice(-3), "itc_memo", "GST ITC memo", 2611, "issued"]]; docs.forEach(([id, type, title, total, status]) => DB().insert("documents", { id, type, title, batch, total, status, at: new Date().toISOString(), org: "o-munchly" })); DB().update("batches", batch, { status: "settled" }); DB().audit(by, "issued document pack", batch); notifyRole("sustainability", { title: "Ledger ready · " + batch, body: "217.6 kg kept out of landfill with invoices behind every kilo. Write the BRSR row.", link: "impact" }); notifyRole("operator", { title: "Papers ready · " + batch, body: "Invoice, credit note, e-way bill check, GST memo. Nothing to chase.", link: "batches/" + batch + "/documents" }); });
  Bus.subscribe("ledger.closed", ({ batch, by }) => { DB().insert("ledger", { batch, recovered: 21222, writeoffAvoided: 21760, itc: 2611, disposalAvoided: 3346, kg: 217.6, co2: 0.41, meals: 0, closedAt: new Date().toISOString() }); DB().update("batches", batch, { status: "cleared", closedAt: new Date().toISOString(), recovered: 21222, kg: 217.6 }); DB().audit(by, "closed ledger", batch); notifyRole("operator", { title: "Batch closed · 0 cartons binned", body: "₹21,222 recovered, ₹2,611 GST credit kept, 217.6 kg out of landfill. " + batch + " is cleared.", link: "batches/" + batch }); });
  Bus.subscribe("user.invited", ({ user, by }) => { const u = DB().user(user); notifyRole("admin", { title: "New user invited", body: u.name + " (" + u.role + ") invited by " + ((DB().user(by) || {}).name || "system") + ".", link: "admin/users" }); });

  window.Bus = Bus;
})();
