// Smart-Clearance app v2 · the trade: distributor (home, photos, rounds, orders, stock), retailer (offers, orders, shop), buyer (listings, bids, orders), food bank (pickups)
(function () {
  const { useState, useEffect } = React;
  const { motion, AnimatePresence } = Motion;
  const K = window.SC2; const A = window.SC_APP;
  const { Icon, Avatar, Mark, Btn, Chip, Plate, Sheet, Input, Field, Select, Stepper, TopBar, RunHead, Ticks, Empty, LiveTile, ModeSwitch, Emblem, inr, num, inrDec, cx } = K;
  const { useDB, DataTable, Toolbar, Pills, PageHead, StatusChip, KV, ConfirmSheet, FormSheet, Who, ago, when, CARTON } = A;
  const DB = window.DB, Bus = window.Bus, Auth = window.Auth; const IMG = window.SC2_IMG;
  const Bar = ({ user, nav, title, back, onBack, runhead }) => <TopBar who={!title && !back ? { name: user.name, img: user.avatar, role: (DB.org(user.org) || {}).name + " · " + (DB.org(user.org) || {}).city } : undefined} title={title} back={back} onBack={onBack} runhead={runhead} unread={DB.list("notifications", { where: { user: user.id, read: false } }).length} onBell={() => nav("notifications")}><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} /></TopBar>;

  /* ---------- distributor ---------- */
  function DistHome({ user, nav }) {
    const v = useDB(); const mine = DB.list("batches", { where: { org: user.org } }).sort((a, b) => a.daysLeft - b.daysLeft);
    const asks = mine.filter(b => b.photo && b.photo.status === "requested"); const rounds = DB.list("shipments", { where: { org: user.org } }).filter(s => s.status !== "done");
    const orders = DB.list("orders", { where: { org: user.org, type: "shop" } });
    return <><Bar user={user} nav={nav} runhead={<RunHead parts={[{ b: "Godown" }, { b: String(mine.length), t: "batches" }, { b: String(asks.length), t: "photo asked", hot: asks.length > 0 }, { b: String(rounds.length), t: "rounds" }]} />} />
      <div className="page trade">
        <h1>Namaste, {user.name.split(" ")[0]} bhai</h1>
        {asks.map(b => <Plate key={b.id} tone="ultra" framed className="stack register"><div className="row"><Mark size="sm" sun={false} /><b>Smart-Clearance · {when(b.photo.at)}</b></div><p className="hi" style={{ fontSize: 18 }}>{user.name.split(" ")[0]} bhai, ek photo chahiye: {(DB.product(b.product) || {}).name}, batch {b.id}, carton ka label. Bas ek.</p><Btn kind="yes" size="lg" icon="camera" onClick={() => nav("photos/" + b.id)}>Take the photo</Btn></Plate>)}
        {rounds.map(r => <Plate key={r.id} className="stack-sm register"><div className="row between"><b>{r.label}</b><StatusChip status={r.status === "planned" ? "planned_round" : r.status} /></div><p className="t-small muted">{r.stops} drops · {r.done} done</p><Btn kind="primary" icon="truck" onClick={() => nav("rounds/" + r.id)}>Open the round</Btn></Plate>)}
        <Plate className="stack-sm"><div className="row between"><h3>My godown</h3><Btn kind="ghost" size="sm" onClick={() => nav("stock")}>All stock <Icon name="right" size={16} /></Btn></div>{mine.slice(0, 5).map(b => <div key={b.id} className="row between" style={{ padding: "8px 0", borderBottom: "var(--kl-thin) solid var(--line)" }}><div><b>{(DB.product(b.product) || {}).name}</b><div className="t-xs muted mono">{b.id} · {b.cartons} cartons</div></div><Chip tone={b.status === "at_risk" ? "vermilion" : ["executing", "approved", "cleared"].includes(b.status) ? "ultra" : "emerald"} icon="clock">{b.daysLeft} d</Chip></div>)}</Plate>
        <Plate className="row between"><div><b>{orders.length} shop orders</b><div className="t-small muted">{num(orders.reduce((t, o) => t + o.qty, 0))} packets from the schemes</div></div><Btn kind="ghost" size="sm" onClick={() => nav("orders")}>See orders <Icon name="right" size={16} /></Btn></Plate>
      </div></>;
  }
  function Photos({ user, nav, id }) {
    const v = useDB(); const mine = DB.list("batches", { where: { org: user.org } }).filter(b => b.photo && b.photo.status !== "none");
    if (id) return <Camera user={user} nav={nav} batch={DB.get("batches", id)} />;
    return <><Bar user={user} nav={nav} title="Label photos" />
      <div className="page trade"><PageHead title="Label photos" sub="The agent prices nothing until one carton label is photographed on the shelf." />
        {!mine.length ? <Plate><Empty icon="camera" title="No photo requested" body="Requests arrive as a push when the agent needs the truth from the shelf." /></Plate> : mine.map(b => <Plate key={b.id} className="row between wrap"><div><b>{(DB.product(b.product) || {}).name}</b><div className="t-xs muted mono">{b.id} · {b.photo.status === "requested" ? "asked " + ago(b.photo.at) : "sent " + ago(b.photo.at)}</div></div>{b.photo.status === "requested" ? <Btn kind="yes" icon="camera" onClick={() => nav("photos/" + b.id)}>Take the photo</Btn> : <Chip tone={b.photo.status === "verified" ? "emerald" : "chrome"} icon={b.photo.status === "verified" ? "check" : "clock"}>{b.photo.status}</Chip>}</Plate>)}
      </div></>;
  }
  function Camera({ user, nav, batch }) {
    const [phase, setPhase] = useState("view"); const p = batch ? DB.product(batch.product) : null;
    const shoot = () => { setPhase("flash"); setTimeout(() => setPhase("reading"), 350); setTimeout(() => setPhase("result"), 2300); };
    if (!batch) return <><Bar user={user} nav={nav} back="Photos" onBack={() => nav("photos")} /><div className="page"><Plate><Empty icon="camera" title="No such batch" /></Plate></div></>;
    if (batch.photo.status !== "requested") return <><Bar user={user} nav={nav} back="Photos" onBack={() => nav("photos")} /><div className="page trade"><h1>Label photo sent</h1><Plate className="labelcard"><div className="labelphoto"><img className="real" src={CARTON} alt="Carton label photo" /><span className="ver"><Chip tone="emerald" solid icon="check">{batch.photo.status === "verified" ? "Verified " + when(batch.photo.at) : "Reading"}</Chip></span></div><div className="stack-sm"><p className="t-small muted">Gemini read the batch, both dates and the MRP straight off the pack. The brand has the plan now.</p><Btn onClick={() => nav("home")}>Back home</Btn></div></Plate></div></>;
    return <div className="cam">
      <div className="camtop"><button type="button" className="btn ghost sm" style={{ color: "#fff" }} onClick={() => nav("photos")}>Cancel</button><span className="mono t-xs">{batch.id} · carton label</span><span style={{ width: 60 }} /></div>
      <div className="vf"><img src={CARTON} alt="" />
        {(phase === "view" || phase === "flash") && <div className="frame" aria-hidden="true" />}
        <AnimatePresence>{phase === "flash" && <motion.div key="flash" className="flash" initial={{ opacity: 0 }} animate={{ opacity: [0, 0.95, 0] }} transition={{ duration: 0.5 }} />}</AnimatePresence>
        {phase === "reading" && <motion.div className="scanline" initial={{ top: "14%" }} animate={{ top: ["14%", "86%", "14%"] }} transition={{ duration: 1.8, ease: "linear" }} />}
        {phase === "view" && <div className="hint">Fill the frame with the label on one carton</div>}
        {phase === "reading" && <div className="hint"><span className="row" style={{ justifyContent: "center" }}><span className="spinner" style={{ width: 14, height: 14 }} />Gemini is reading the label…</span></div>}
        <AnimatePresence>{phase === "result" && <motion.div key="res" className="result" initial={{ y: 40, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ type: "spring", stiffness: 380, damping: 32 }}><Plate className="stack-sm"><div className="row between"><b>Read in 1.2 s</b><Chip tone="emerald" solid icon="check">confidence 0.97</Chip></div><KV items={[["Batch", batch.id], ["Best before", batch.bestBefore], ["MRP", inr(p.mrp) + " · " + p.perCarton + " a carton"], ["Records", "match"]]} /><Btn kind="yes" size="lg" icon="send" onClick={() => { Bus.publish("photo.sent", { batch: batch.id, by: user.id }); DB.audit(user.id, "sent label photo", batch.id, "phone"); nav("photos"); }}>Send to the brand</Btn></Plate></motion.div>}</AnimatePresence>
      </div>
      <div className="shutterbar">{phase === "view" ? <button type="button" className="shutter" onClick={shoot} aria-label="Take photo"><i /></button> : phase === "result" ? <Btn onClick={() => setPhase("view")}>Retake</Btn> : <span className="t-small" aria-live="polite">{phase === "flash" ? "Captured" : "Reading…"}</span>}</div>
    </div>;
  }
  function Rounds({ user, nav, id }) {
    const v = useDB(); const list = DB.list("shipments", { where: { org: user.org }, sort: ["at", "desc"] }); const r = id ? DB.get("shipments", id) : null;
    const [running, setRunning] = useState(false);
    useEffect(() => { if (!running || !r) return; if (r.done >= r.stops) { setRunning(false); DB.update("shipments", r.id, { status: "done" }); return; } const t = setTimeout(() => DB.update("shipments", r.id, { done: r.done + 1, status: "running" }), 320); return () => clearTimeout(t); }, [running, r && r.done]);
    if (r) { const b = DB.get("batches", r.batch); const online = DB.list("orders", { where: { batch: r.batch, type: "online" } })[0]; const shops = DB.all("shops"); const dispatched = b && ["settling", "settled", "cleared"].includes(b.status);
      return <><Bar user={user} nav={nav} back="Rounds" onBack={() => nav("rounds")} runhead={<RunHead parts={[{ b: r.label }, { b: String(r.done), t: "of " + r.stops + " drops" }]} />} />
        <div className="page trade"><h1>{r.label}</h1>
          <Plate className="row wrap"><div className="grow"><b>{r.done} of {r.stops} drops done</b><div className="t-small muted">{num(shops.reduce((t, s) => t + s.typicalQty, 0))} packets on board · one or two cartons a shop</div></div>{r.done < r.stops && <Btn kind="primary" icon="truck" loading={running} onClick={() => setRunning(true)}>{r.done ? "Resume" : "Start the round"}</Btn>}{r.done >= r.stops && !dispatched && (online ? <Btn kind="yes" icon="box" onClick={() => Bus.publish("shipment.dispatched", { batch: r.batch, by: user.id })}>Dispatch the Hyderabad lot</Btn> : <Chip tone="chrome" icon="clock">Hyderabad lot waits for the buyer's balance</Chip>)}{dispatched && <Chip tone="emerald" solid icon="check">Dispatched</Chip>}</Plate>
          <div className="progress"><i style={{ width: (r.done / r.stops * 100) + "%" }} /></div>
          <Plate><div className="route">{shops.slice(0, r.stops).map((s, i) => <div key={s.id} className={cx("stop", i < r.done && "done")}><i>{i < r.done ? <Icon name="check" size={14} /> : i + 1}</i><div><div className="sn">{s.name}</div><div className="sa">{s.area}</div></div><b>{s.typicalQty}</b></div>)}</div></Plate>
        </div></>; }
    return <><Bar user={user} nav={nav} title="Van rounds" />
      <div className="page trade"><PageHead title="Van rounds" sub="Drops appear here when the brand approves a plan. The van keeps its normal round." />
        {!list.length ? <Plate><Empty emblem={IMG + "emblem-van.webp"} title="No rounds yet" /></Plate> : list.map(s => <Plate key={s.id} as="button" type="button" className="row between wrap" style={{ textAlign: "left", width: "100%" }} onClick={() => nav("rounds/" + s.id)}><div><b>{s.label}</b><div className="t-xs muted mono">{s.batch} · {s.done}/{s.stops} · {ago(s.at)}</div></div><StatusChip status={s.status === "planned" ? "planned_round" : s.status} /></Plate>)}
      </div></>;
  }
  function DistOrders({ user, nav }) { return <A.Orders user={user} nav={nav} scope={o => o.org === user.org || o.type === "shop"} />; }
  function Stock({ user, nav }) {
    const v = useDB(); const rows = DB.list("batches", { where: { org: user.org }, sort: ["daysLeft", "asc"] });
    return <><Bar user={user} nav={nav} title="Stock" />
      <div className="page trade"><PageHead title="Stock in my godown" sub={(DB.org(user.org) || {}).godown} />
        <DataTable rows={rows} columns={[{ key: "product", label: "Product", render: b => <span className="cellwho"><span><b>{(DB.product(b.product) || {}).name}</b><span>{b.id}</span></span></span> }, { key: "daysLeft", label: "Days", n: true }, { key: "cartons", label: "Cartons", n: true }, { key: "status", label: "Status", render: b => <StatusChip status={b.status} /> }]} />
      </div></>;
  }

  /* ---------- retailer ---------- */
  function Offers({ user, nav, id }) {
    const v = useDB(); const org = DB.org(user.org) || {}; const shop = DB.all("shops").find(s => s.name === org.name) || DB.all("shops")[0];
    const offers = DB.list("offers", { sort: ["at", "desc"] }); const [qty, setQty] = useState(24); const [busy, setBusy] = useState(false);
    const pay = q => q / 12 * 10 * 18, margin = q => q * 30 - pay(q);
    const mine = o => DB.list("orders", { where: { offer: o.id, shop: shop.id } })[0];
    const place = o => { setBusy(true); setTimeout(() => { const ord = DB.insert("orders", { type: "shop", batch: o.batch, party: org.name + " · " + (org.city || ""), shop: shop.id, qty, price: 18, status: "confirmed", at: new Date().toISOString(), org: "o-rakesh", offer: o.id }); Bus.publish("order.placed", { batch: o.batch, shop: shop.id, qty }); DB.audit(user.id, "accepted offer", o.id + " · " + qty + " packets", "phone"); setBusy(false); }, 900); };
    return <><Bar user={user} nav={nav} runhead={<RunHead parts={[{ b: "आज के ऑफर" }, { b: String(offers.filter(o => o.status === "live").length), t: "live" }]} />} />
      <div className="page trade"><h1 className="hi" style={{ fontFamily: "var(--font-hi)", fontWeight: 800 }}>आज के ऑफर</h1>
        {!offers.length ? <Plate><Empty emblem={IMG + "emblem-shop.webp"} title="आज कोई ऑफर नहीं" body="ऑफर आते ही यहाँ और नोटिफिकेशन में दिखेगा." /></Plate> : offers.map(o => { const p = DB.product((DB.get("batches", o.batch) || {}).product) || {}; const ord = mine(o); return ord ? <Plate key={o.id} className="offer stack register"><div className="row between"><Mark size="sm" sun={false} /><Chip tone="emerald" solid icon="check">ऑर्डर हो गया · {when(ord.at)}</Chip></div><div className="obig">{ord.qty} पैकेट · {inr(pay(ord.qty))}</div><p className="hi">राकेश भाई की वैन मंगलवार को लाएगी. पैसा डिलीवरी पर.</p><div className="ledger"><div className="lrow"><span className="hi">आप बेचेंगे {ord.qty} × ₹30</span><span className="v">{inr(ord.qty * 30)}</span></div><div className="lrow pos sum"><span className="hi">आपका मार्जिन</span><span className="v">{inr(margin(ord.qty))}</span></div></div><Btn kind="ghost" onClick={() => nav("myorders")}>मेरे ऑर्डर <Icon name="right" size={16} /></Btn></Plate>
          : <Plate key={o.id} className="offer stack register"><div className="row between"><div className="row"><Mark size="sm" sun={false} /><span className="t-xs muted mono">{when(o.at)} · Munchly Foods</span></div><Chip tone="chrome" solid icon="clock">{o.windowHours} घंटे</Chip></div>{p.plate && <img src={p.plate} alt="" style={{ width: 110, justifySelf: "center" }} />}<div className="obig">{p.name} · 10 पैकेट लो, 2 मुफ़्त</div><div className="scheme"><div><b>₹{o.price}</b><span>प्रति पैकेट</span></div><div><b>+2</b><span>हर 10 पर मुफ़्त</span></div><div><b>₹{p.mrp}</b><span>MRP</span></div></div><Field label={<span className="hi">कितने पैकेट?</span>} help={<span className="hi">{qty / 24} कार्टन · आप देंगे {inr(pay(qty))} · मार्जिन {inr(margin(qty))}</span>}><Stepper value={qty} onChange={setQty} min={12} max={120} step={12} label="packets" /></Field><Btn kind="yes" size="lg" full icon="check" loading={busy} onClick={() => place(o)}><span className="hi">ऑर्डर करें</span> · {qty} packets</Btn><p className="t-xs muted hi">डिलीवरी मंगलवार, राकेश ट्रेडर्स की वैन · पैसा डिलीवरी पर</p></Plate>; })}
      </div></>;
  }
  function MyOrders({ user, nav }) {
    const v = useDB(); const org = DB.org(user.org) || {}; const shop = DB.all("shops").find(s => s.name === org.name) || DB.all("shops")[0]; const rows = DB.list("orders", { where: { shop: shop.id }, sort: ["at", "desc"] });
    return <><Bar user={user} nav={nav} title="मेरे ऑर्डर" /><div className="page trade"><h1 className="hi" style={{ fontFamily: "var(--font-hi)", fontWeight: 800 }}>मेरे ऑर्डर</h1>{!rows.length ? <Plate><Empty icon="store" title="अभी कोई ऑर्डर नहीं" /></Plate> : rows.map(o => <Plate key={o.id} className="row between"><div><b>{(DB.product((DB.get("batches", o.batch) || {}).product) || {}).name} · {o.qty} पैकेट</b><div className="t-small muted">{when(o.at)} · {inr(o.qty / 12 * 10 * o.price)}</div></div><StatusChip status={o.status} /></Plate>)}</div></>;
  }
  function Shop({ user, nav }) {
    const v = useDB(); const org = DB.org(user.org) || {}; const [name, setName] = useState(org.name); const [saved, setSaved] = useState(false);
    return <><Bar user={user} nav={nav} title="My shop" /><div className="page trade"><PageHead title="My shop" sub={org.cluster + " cluster"} /><Plate className="stack"><Field label="Shop name" id="sn"><Input id="sn" value={name} onChange={e => setName(e.target.value)} /></Field><KV items={[["Area", org.city], ["Cluster", org.cluster], ["Phone", user.phone], ["Language", user.lang === "hi" ? "हिन्दी" : user.lang === "mr" ? "मराठी" : "English"]]} /><div className="row wrap"><Btn kind="primary" icon="check" onClick={() => { DB.update("orgs", org.id, { name }); DB.audit(user.id, "updated shop", org.id, "phone"); setSaved(true); setTimeout(() => setSaved(false), 1500); }}>Save</Btn>{saved && <Chip tone="emerald" icon="check">saved</Chip>}</div></Plate></div></>;
  }

  /* ---------- buyer (ExpireSoon) ---------- */
  function ESTop({ sub, user, nav }) { return <div className="es-top"><span className="esword">EXPIRESOON</span><span className="t-xs">{sub}</span><div className="grow" /><button type="button" className="iconbtn" style={{ color: "inherit" }} aria-label="Notifications" onClick={() => nav("notifications")}><Icon name="bell" />{DB.list("notifications", { where: { user: user.id, read: false } }).length ? <span className="badge">{DB.list("notifications", { where: { user: user.id, read: false } }).length}</span> : null}</button><ModeSwitch /><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} /></div>; }
  function Listings({ user, nav, id }) {
    const v = useDB(); const list = DB.list("listings", { sort: ["at", "desc"] }); const l = id ? DB.get("listings", id) : null;
    const [bid, setBid] = useState(13); const [busy, setBusy] = useState(false);
    if (l) { const b = DB.get("batches", l.batch) || {}; const p = DB.product(b.product) || {}; const bids = DB.list("bids", { where: { listing: l.id, by: user.org }, sort: ["at", "asc"] }); const last = bids[bids.length - 1]; const order = DB.list("orders", { where: { batch: l.batch, type: "online", org: user.org } })[0];
      const place = () => { setBusy(true); setTimeout(() => { const bd = DB.insert("bids", { listing: l.id, by: user.org, price: bid, status: "placed", at: new Date().toISOString() }); Bus.publish("bid.placed", { listing: l.id, bid: bd.id }); DB.audit(user.id, "placed bid", l.id + " · " + inrDec(bid)); setBusy(false); }, 600); };
      const accept = () => { DB.update("bids", last.id, { status: "accepted" }); Bus.publish("bid.accepted", { listing: l.id, bid: last.id, price: last.counter }); DB.audit(user.id, "accepted counter", l.id + " · " + inrDec(last.counter)); };
      return <div style={{ minHeight: "100%" }}><ESTop sub="listing" user={user} nav={nav} /><div className="page"><button type="button" className="backbtn" onClick={() => nav("listings")}><Icon name="left" size={20} />Listings</button>
        <div className="listinggrid"><div className="stack-sm"><div className="listimg"><img src={CARTON} alt="Carton, label photo verified" /></div><div className="row wrap"><Chip tone="emerald" icon="check">label photo verified</Chip><Chip icon="clock">best before {b.bestBefore} · {b.daysLeft} days</Chip><Chip icon="pin">{(DB.org(b.org) || {}).city} · dispatch 24 h after balance</Chip></div></div>
          <div className="stack"><div><h1 style={{ fontFamily: "var(--font-ui)", fontWeight: 800, fontSize: 24 }}>{p.name}</h1><p className="muted t-small">{num(l.qty)} packets · batch {l.batch} · seller {(DB.org(b.org) || {}).name} via Smart-Clearance</p></div><div className="es-price">{inr(l.price)}<small style={{ fontSize: 16, fontFamily: "var(--font-ui)", fontWeight: 400, color: "var(--ink-2)" }}> / packet</small><s>MRP ₹{p.mrp}</s></div>
            {l.status === "awarded" && order ? <Plate className="stack-sm"><Chip tone="emerald" solid icon="check">Order {order.id} · awarded at {inrDec(order.price)}</Chip><div className="ledger"><div className="lrow"><span>{num(order.qty)} × {inrDec(order.price)}</span><span className="v">{inr(order.qty * order.price)}</span></div><div className="lrow pos"><span>Token paid (15%)</span><span className="v">{inr(order.token)}</span></div><div className="lrow sum"><span>Balance before dispatch</span><span className="v">{inr(order.balance)}</span></div></div>{order.status === "token_paid" ? <Btn kind="market" icon="rupee" onClick={() => { DB.update("orders", order.id, { status: "paid" }); DB.audit(user.id, "paid balance", order.id); }}>Pay the balance · {inr(order.balance)}</Btn> : <Chip tone="ultra" icon="check">Balance paid · dispatch within 24 h</Chip>}</Plate>
            : l.status === "awarded" ? <Plate tone="violet-soft"><b>Awarded to another buyer</b><p className="t-small">This lot went at {inrDec(l.awardedPrice)}.</p></Plate>
            : <Plate className="stack-sm"><Field label="Your bid per packet" help={"For all " + num(l.qty) + " packets · 15% token on acceptance"} id="bid"><Input id="bid" mono type="number" inputMode="decimal" step="0.1" min="10" max={l.price} value={bid} onChange={e => setBid(parseFloat(e.target.value) || 0)} disabled={!!last && last.status !== "countered"} /></Field>
              {(!last || last.status === "countered") && <Btn kind="market" size="lg" full icon="tag" loading={busy} onClick={place}>{last ? "Bid again · " : "Place bid · "}{inrDec(bid)}</Btn>}
              <div className="chat">{bids.map(bd => <React.Fragment key={bd.id}><div className="msg me"><Avatar person={{ name: user.name, img: user.avatar }} size="md" /><div className="bub">{inrDec(bd.price)} a packet for all {num(l.qty)}?<small>{user.name.split(" ")[0]} · {when(bd.at)}</small></div></div>{bd.status === "placed" && <div className="msg"><Mark size="sm" sun={false} /><div className="bub ag dots" aria-label="Agent is typing"><span /><span /><span /></div></div>}{bd.status === "countered" && <div className="msg"><Mark size="sm" sun={false} /><div className="bub ag">{inrDec(bd.counter)}, {(DB.org(b.org) || {}).city} stock, dispatch within 24 hours of the balance.<small>Negotiator agent as {(DB.org(b.org) || {}).name}</small></div></div>}{bd.status === "accepted" && <div className="msg"><Mark size="sm" sun={false} /><div className="bub ag">Done at {inrDec(bd.counter || bd.price)}. Token due now.<small>Negotiator agent</small></div></div>}</React.Fragment>)}</div>
              {last && last.status === "countered" && <Btn kind="market" size="lg" full icon="check" onClick={accept}>Accept {inrDec(last.counter)} · pay token {inr(Math.round(l.qty * last.counter * 0.15))}</Btn>}
            </Plate>}
          </div></div></div></div>; }
    return <div style={{ minHeight: "100%" }}><ESTop sub="clearance marketplace · mocked for the prototype" user={user} nav={nav} /><div className="page"><PageHead title="Listings" sub="Short-dated lots from brands, with the label photo and dates visible." />
      {!list.length ? <Plate><Empty emblem={IMG + "emblem-ship.webp"} title="No live listings today" body="Listings appear the moment a brand approves a plan." /></Plate> : <DataTable rows={list.map(l => ({ ...l, productName: (DB.product((DB.get("batches", l.batch) || {}).product) || {}).name, days: (DB.get("batches", l.batch) || {}).daysLeft }))} onRow={l => nav("listings/" + l.id)} columns={[{ key: "productName", label: "Lot", render: l => <span className="cellwho"><span><b>{l.productName}</b><span>{l.id} · {l.batch}</span></span></span> }, { key: "qty", label: "Packets", n: true, render: l => num(l.qty) }, { key: "price", label: "Ask", n: true, render: l => inr(l.price) }, { key: "days", label: "Days left", n: true }, { key: "status", label: "Status", render: l => <StatusChip status={l.status} /> }, { key: "x", label: "", sortable: false, render: l => <Btn kind="market" size="sm" onClick={() => nav("listings/" + l.id)}>{l.status === "live" ? "Bid" : "Open"}</Btn> }]} />}
    </div></div>;
  }
  function Bids({ user, nav }) {
    const v = useDB(); const rows = DB.list("bids", { where: { by: user.org }, sort: ["at", "desc"] }).map(bd => ({ ...bd, listingDoc: DB.get("listings", bd.listing) }));
    return <div style={{ minHeight: "100%" }}><ESTop sub="my bids" user={user} nav={nav} /><div className="page"><PageHead title="My bids" />
      <DataTable rows={rows} onRow={bd => nav("listings/" + bd.listing)} empty={<Empty icon="tag" title="No bids yet" />} columns={[{ key: "listing", label: "Listing", render: bd => <span className="mono">{bd.listing}</span> }, { key: "price", label: "Bid", n: true, render: bd => inrDec(bd.price) }, { key: "counter", label: "Counter", n: true, render: bd => bd.counter ? inrDec(bd.counter) : "—" }, { key: "status", label: "Status", render: bd => <StatusChip status={bd.status} /> }, { key: "at", label: "When", render: bd => <span className="t-xs muted mono">{ago(bd.at)}</span> }]} /></div></div>;
  }
  function BuyOrders({ user, nav }) {
    const v = useDB(); const rows = DB.list("orders", { where: { org: user.org }, sort: ["at", "desc"] });
    return <div style={{ minHeight: "100%" }}><ESTop sub="my orders" user={user} nav={nav} /><div className="page"><PageHead title="Orders and payments" />
      <DataTable rows={rows} empty={<Empty icon="rupee" title="No orders yet" />} columns={[{ key: "id", label: "Order", render: o => <b className="mono">{o.id}</b> }, { key: "batch", label: "Batch", render: o => <span className="mono">{o.batch}</span> }, { key: "qty", label: "Packets", n: true, render: o => num(o.qty) }, { key: "price", label: "Rate", n: true, render: o => inrDec(o.price) }, { key: "balance", label: "Balance due", n: true, render: o => o.status === "token_paid" ? inr(o.balance) : "—" }, { key: "status", label: "Status", render: o => <StatusChip status={o.status} /> }, { key: "x", label: "", sortable: false, render: o => o.status === "token_paid" ? <Btn kind="market" size="sm" onClick={() => { DB.update("orders", o.id, { status: "paid" }); DB.audit(user.id, "paid balance", o.id); }}>Pay balance</Btn> : null }]} /></div></div>;
  }
  function Pickups({ user, nav }) {
    const v = useDB(); const rows = DB.list("orders", { where: { type: "donation" }, sort: ["at", "desc"] });
    return <><Bar user={user} nav={nav} title="Pickups" /><div className="page trade"><PageHead title="Pickups" sub="Surplus packed food booked for collection, with the FSSAI checklist attached." />
      <DataTable rows={rows} empty={<Empty emblem={IMG + "emblem-sun.webp"} title="No pickups booked" />} columns={[{ key: "batch", label: "Batch", render: o => <span className="mono">{o.batch}</span> }, { key: "qty", label: "Packs", n: true }, { key: "party", label: "From", render: o => (DB.org((DB.get("batches", o.batch) || {}).org) || {}).name }, { key: "status", label: "Status", render: o => <StatusChip status={o.status} /> }, { key: "x", label: "", sortable: false, render: o => o.status !== "collected" ? <Btn kind="primary" size="sm" icon="check" onClick={() => { DB.update("orders", o.id, { status: "collected" }); DB.audit(user.id, "confirmed pickup", o.id); }}>Collected</Btn> : null }]} /></div></>;
  }

  window.SC_APP = Object.assign(window.SC_APP, { DistHome, Photos, Rounds, DistOrders, Stock, Offers, MyOrders, Shop, Listings, Bids, BuyOrders, Pickups });
})();
