// Smart-Clearance app v2 · brand operations: Today, Batches, batch detail (overview, verification, plan, execution, documents, timeline), Approvals, Orders, Partners, Reports
(function () {
  const { useState, useEffect, useMemo } = React;
  const { motion, AnimatePresence } = Motion;
  const K = window.SC2; const A = window.SC_APP;
  const { Icon, Avatar, Mark, Btn, Chip, Plate, Sheet, Input, Field, Select, TopBar, RunHead, Stages, Timeline, Label, Door, Tape, LiveTile, Notice, Gate, Ticks, Empty, Skeleton, CountUp, Tabs, inr, num, inrDec, cx } = K;
  const { useQuery, useDoc, useDB, DataTable, Toolbar, Pills, PageHead, StatusChip, KV, ConfirmSheet, FormSheet, Actions, Who, ago, when } = A;
  const DB = window.DB, Bus = window.Bus, Auth = window.Auth;
  const IMG = window.SC2_IMG; const CARTON = DB.PORTRAITS + "01-carton.jpg";
  const DOOR_META = { shops: { short: "SHOPS", name: "Local kirana shops", rule: "₹18 a packet, less ₹12 van delivery · 20+ days · cap 24½ cartons", cls: "sel" }, online: { short: "EXPIRESOON", name: "ExpireSoon marketplace", rule: "₹15 a packet, no cap · 30+ days", cls: "es" }, d2c: { short: "D2C", name: "Brand's own site", rule: "₹15 a packet, less ₹72 courier · cap 6 cartons" }, staff: { short: "STAFF", name: "Staff sale", rule: "₹12 a packet · cap 6 cartons" }, bank: { short: "FOOD BANK", name: "Feeding India", rule: "freight only · meals, not rupees", cls: "fb" }, bin: { short: "THE BIN", name: "Write off", rule: "stock + GST credit back + disposal + EPR", cls: "bin" } };
  const labelState = b => b.status === "at_risk" ? "risk" : ["cleared", "settled", "settling"].includes(b.status) ? "cleared" : ["approved", "executing", "planned", "verifying"].includes(b.status) ? "cleared" : b.status === "written_off" ? "risk" : (b.gates && b.gates.blinkit && b.gates.zepto) ? "safe" : "gated";
  const toLabel = b => ({ id: b.id, days: b.daysLeft, cartons: b.cartons, where: (DB.org(b.org) || {}).name + " · " + (DB.org(b.org) || {}).city, sell: b.sellPerDay, binCost: b.binCost, bestBefore: b.bestBefore, zone: labelState(b) });

  /* ---------- Today ---------- */
  function Today({ user, nav }) {
    const v = useDB(); const [filter, setFilter] = useState("all");
    const batches = DB.all("batches"); const rules = DB.rules();
    const list = batches.filter(b => filter === "all" ? !["written_off"].includes(b.status) : filter === "risk" ? b.status === "at_risk" : filter === "exec" ? ["planned", "approved", "executing", "settling", "settled", "verifying"].includes(b.status) : filter === "watch" ? b.status === "watching" : b.status === "cleared").sort((a, b) => (a.status === "at_risk" ? -1 : 0) - (b.status === "at_risk" ? -1 : 0) || a.daysLeft - b.daysLeft);
    const counts = { all: batches.filter(b => b.status !== "written_off").length, risk: batches.filter(b => b.status === "at_risk").length, exec: batches.filter(b => ["planned", "approved", "executing", "settling", "settled", "verifying"].includes(b.status)).length, watch: batches.filter(b => b.status === "watching").length, cleared: batches.filter(b => b.status === "cleared").length };
    const hot = batches.find(b => b.status === "at_risk"); const stake = batches.filter(b => b.status === "at_risk").reduce((t, b) => t + (b.binCost || 0), 0);
    const recovered = DB.all("ledger").reduce((t, l) => t + (l.recovered || 0), 0), kg = DB.all("ledger").reduce((t, l) => t + (l.kg || 0), 0);
    const [running, setRunning] = useState(false);
    const runWatcher = () => { setRunning(true); setTimeout(() => { Bus.publish("watcher.run", { by: user.id }); setRunning(false); }, 1400); };
    const lastRun = DB.list("audit", { where: { what: "watcher run" }, sort: ["at", "desc"], limit: 1 })[0];
    return <>
      <TopBar who={{ name: user.name, img: user.avatar, role: user.title + " · " + (DB.org(user.org) || {}).name }} runhead={<RunHead parts={[{ b: "Today" }, { b: String(counts.all), t: "batches" }, { b: String(counts.risk), t: "at risk", hot: counts.risk > 0 }, { b: inr(stake), t: "at stake", hot: stake > 0 }]} />} unread={DB.list("notifications", { where: { user: user.id, read: false } }).length} onBell={() => nav("notifications")}><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} onAdmin={() => nav("users")} /></TopBar>
      <div className="page">
        <div className="dash">
          <div className="stack">
            <PageHead title="Today" sub={new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long" }) + " · Watcher last ran " + (lastRun ? ago(lastRun.at) : "never")} />
            <Pills options={[{ id: "all", label: "All", count: counts.all }, { id: "risk", label: "At risk", count: counts.risk }, { id: "exec", label: "In motion", count: counts.exec }, { id: "watch", label: "Watching", count: counts.watch }, { id: "cleared", label: "Cleared", count: counts.cleared }]} value={filter} onChange={setFilter} />
            <div className="sheetgrid">{list.map(b => { const p = DB.product(b.product); const isHot = b.status === "at_risk"; return <Label key={b.id} batch={toLabel(b)} product={p} state={labelState(b)} hot={isHot} img={isHot ? IMG + "hero-carton.webp" : undefined} onOpen={() => nav("batches/" + b.id)} action={isHot ? <Btn kind="yes" size="sm" icon="arrow" onClick={() => nav("batches/" + b.id)}>Open the batch</Btn> : <StatusChip status={b.status} />}>{b.routed && <Chip tone="ultra" icon="check">routed</Chip>}</Label>; })}{!list.length && <Plate style={{ gridColumn: "1 / -1" }}><Empty emblem={IMG + "emblem-sun.webp"} title="Nothing in this filter" body="Change the filter or run the Watcher." /></Plate>}</div>
          </div>
          <aside className="aside">
            <Notice who="Watcher" when={"daily " + rules.watchTime + " IST · " + (lastRun ? lastRun.target : "not run yet")}>
              {hot ? <><p className="t-small">One batch fails both checks: the delivery-app date gates and real sell-through in its pincode.</p><div><Gate app="Blinkit" rule={"needs " + rules.gates.blinkit + " days · has " + hot.daysLeft} ok={hot.gates ? hot.gates.blinkit : false} /><Gate app="Zepto" rule={"needs " + Math.round(rules.gates.zepto * 100) + "% of life"} ok={hot.gates ? hot.gates.zepto : false} /><Gate app="Instamart" rule={"needs " + Math.round(rules.gates.instamart * 100) + "% of life"} ok={hot.gates ? hot.gates.instamart : false} /><div className="gate"><span><b>{num(Math.round(hot.atRisk || 0))} packets</b> at risk</span><Chip tone="vermilion" dot>{inr(hot.binCost || 0)} if binned</Chip></div></div><Btn kind="yes" icon="arrow" onClick={() => nav("batches/" + hot.id)}>Open {hot.id}</Btn></> : <><p className="t-small">No batch fails the gates or sell-through right now. The next check runs at {rules.watchTime}.</p><Btn icon="refresh" loading={running} onClick={runWatcher}>Run the Watcher now</Btn></>}
            </Notice>
            <div className="tilerow"><LiveTile value={counts.risk} label="at risk" tone={counts.risk ? "vermilion" : "emerald"} /><LiveTile value={counts.exec} label="in motion" tone="emerald" /><LiveTile value={inr(recovered)} label="recovered, all time" /><LiveTile value={Math.round(kg) + " kg"} label="kept out of landfill" /></div>
          </aside>
        </div>
      </div>
    </>;
  }

  /* ---------- Batches ---------- */
  function Batches({ user, nav }) {
    const v = useDB(); const [q, setQ] = useState(""); const [st, setSt] = useState("all"); const [org, setOrg] = useState("all"); const [sort, setSort] = useState(["daysLeft", "asc"]);
    const rows = DB.list("batches", { search: q }).filter(b => (st === "all" || b.status === st) && (org === "all" || b.org === org)).map(b => ({ ...b, productName: (DB.product(b.product) || {}).name, orgName: (DB.org(b.org) || {}).name }));
    const statuses = ["all", "at_risk", "verifying", "planned", "approved", "executing", "settling", "settled", "cleared", "watching", "written_off"];
    return <>
      <TopBar title="Batches" runhead={<RunHead parts={[{ b: String(rows.length), t: "batches" }, { b: String(DB.all("batches").filter(b => b.status === "at_risk").length), t: "at risk", hot: true }]} />} unread={DB.list("notifications", { where: { user: user.id, read: false } }).length} onBell={() => nav("notifications")}><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} /></TopBar>
      <div className="page">
        <PageHead title="Batches" sub="Every lot the Watcher sees, from the ERP and the distributors' godowns." actions={<Btn icon="download" onClick={() => exportCSV(rows.map(b => ({ batch: b.id, product: b.productName, days: b.daysLeft, cartons: b.cartons, where: b.orgName, status: b.status })), "batches.csv")}>Export</Btn>} />
        <Toolbar search={q} onSearch={setQ} placeholder="Batch, product, godown" count={rows.length}>
          <Select value={st} onChange={e => setSt(e.target.value)} aria-label="Status">{statuses.map(s => <option key={s} value={s}>{s === "all" ? "All statuses" : (A.STATUS[s] || [0, s])[1]}</option>)}</Select>
          <Select value={org} onChange={e => setOrg(e.target.value)} aria-label="Godown"><option value="all">All godowns</option>{DB.list("orgs", { where: { kind: "distributor" } }).map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</Select>
        </Toolbar>
        <DataTable rows={rows} sort={sort} onSort={setSort} onRow={b => nav("batches/" + b.id)} columns={[
          { key: "id", label: "Batch", w: 150, render: b => <span className="cellwho"><span><b className="mono">{b.id}</b><span>{b.productName}</span></span></span> },
          { key: "daysLeft", label: "Days left", n: true, render: b => <span className={cx("mono", b.status === "at_risk" && "urgent")} style={{ color: b.status === "at_risk" ? "var(--vermilion-text)" : undefined }}>{b.daysLeft}</span> },
          { key: "cartons", label: "Cartons", n: true, render: b => num(b.cartons) },
          { key: "packets", label: "Packets", n: true, render: b => num(b.packets) },
          { key: "orgName", label: "Godown" },
          { key: "status", label: "Status", render: b => <StatusChip status={b.status} /> },
          { key: "updatedAt", label: "Updated", render: b => <span className="t-xs muted mono">{ago(b.updatedAt)}</span> },
          { key: "x", label: "", sortable: false, render: b => <Actions items={[{ label: "Open", icon: "eye", onClick: () => nav("batches/" + b.id) }, b.photo && b.photo.status === "none" && { label: "Request a photo", icon: "camera", onClick: () => Bus.publish("photo.requested", { batch: b.id, by: user.id }) }, "-", !["cleared", "written_off"].includes(b.status) && { label: "Write off", icon: "trash", danger: true, onClick: () => nav("batches/" + b.id + "/overview?writeoff=1") }]} /> },
        ]} />
      </div>
    </>;
  }
  function exportCSV(rows, name) { if (!rows.length) return; const keys = Object.keys(rows[0]); const csv = [keys.join(","), ...rows.map(r => keys.map(k => '"' + String(r[k] == null ? "" : r[k]).replace(/"/g, '""') + '"').join(","))].join("\n"); const u = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const el = document.createElement("a"); el.href = u; el.download = name; el.click(); setTimeout(() => URL.revokeObjectURL(u), 1000); }

  /* ---------- Batch detail ---------- */
  function BatchDetail({ user, nav, id, tab = "overview" }) {
    const v = useDB(); const b = DB.get("batches", id);
    if (!b) return <><TopBar back="Batches" onBack={() => nav("batches")} /><div className="page"><Plate><Empty icon="box" title={"No batch " + id} body="It may have been removed from the ERP feed." action={<Btn onClick={() => nav("batches")}>Back to batches</Btn>} /></Plate></div></>;
    const p = DB.product(b.product); const org = DB.org(b.org) || {}; const rules = DB.rules();
    const plan = DB.list("plans", { where: { batch: id }, sort: ["at", "desc"] })[0]; const listing = DB.list("listings", { where: { batch: id } })[0]; const offer = DB.list("offers", { where: { batch: id } })[0];
    const orders = DB.list("orders", { where: { batch: id }, sort: ["at", "desc"] }); const docs = DB.list("documents", { where: { batch: id } }); const ledger = DB.list("ledger", { where: { batch: id } })[0];
    const stage = b.status === "cleared" ? 6 : b.status === "settled" ? 5 : ["settling"].includes(b.status) ? 5 : ["executing", "approved"].includes(b.status) ? 4 : b.status === "planned" ? 3 : b.status === "verifying" ? 2 : (b.photo && b.photo.status === "verified") ? 1 : 0;
    const canOperate = Auth.can("plans.approve") || user.admin;
    const [approve, setApprove] = useState(false); const [reject, setReject] = useState(false); const [reason, setReason] = useState(""); const [writeoff, setWriteoff] = useState(false); const [manual, setManual] = useState(false); const [note, setNote] = useState("");
    useEffect(() => { if (location.hash.includes("writeoff=1")) setWriteoff(true); }, []);
    const tabs = [{ id: "overview", label: "Overview" }, { id: "verification", label: "Verification" }, { id: "plan", label: "Plan", badge: plan && plan.status === "awaiting_approval" ? 1 : 0 }, { id: "execution", label: "Execution" }, { id: "documents", label: "Documents", badge: docs.length || 0 }, { id: "timeline", label: "Timeline" }];
    const head = <RunHead parts={[{ b: b.id }, { b: String(b.daysLeft), t: "days left", hot: b.status === "at_risk" }, { b: num(b.cartons), t: "cartons" }, { b: (A.STATUS[b.status] || [0, b.status])[1] }]} />;
    const events = DB.list("events").filter(e => e.payload && (e.payload.batch === id || (e.payload.flagged || []).includes(id))).concat(DB.list("audit").filter(a => String(a.target).startsWith(id)).map(a => ({ topic: a.what, at: a.at, who: a.who, payload: {} }))).sort((x, y) => new Date(x.at) - new Date(y.at));
    const tl = events.map((e, i) => ({ id: i, who: e.who ? ((DB.user(e.who) || {}).name || e.who) : AGENT_OF[e.topic] || "Agent", text: EVENT_TEXT[e.topic] || e.topic, at: when(e.at), state: "done", human: !!e.who && e.who !== "system", minutes: i === 0 ? 0 : Math.max(0, (new Date(e.at) - new Date(events[i - 1].at)) / 60000) }));
    return <>
      <TopBar back="Batches" onBack={() => nav("batches")} runhead={head} unread={DB.list("notifications", { where: { user: user.id, read: false } }).length} onBell={() => nav("notifications")}><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} /></TopBar>
      <div className="page">
        <div className="stack-sm"><div className="row between wrap"><h1>{p.name}</h1><div className="row wrap">{canOperate && b.photo.status === "none" && b.status !== "cleared" && <Btn kind="primary" icon="camera" onClick={() => Bus.publish("photo.requested", { batch: id, by: user.id })}>Request a label photo</Btn>}{canOperate && plan && plan.status === "awaiting_approval" && <Btn kind="yes" icon="check" onClick={() => nav("batches/" + id + "/plan")}>Review the plan</Btn>}<Actions items={[{ label: "Copy batch id", icon: "copy", onClick: () => navigator.clipboard && navigator.clipboard.writeText(id) }, { label: "Open godown partner", icon: "store", onClick: () => nav("partners/" + b.org) }, "-", canOperate && !["cleared", "written_off"].includes(b.status) && { label: "Write off", icon: "trash", danger: true, onClick: () => setWriteoff(true) }]} /></div></div>
          <div className="row wrap"><Chip mono>{b.id}</Chip><Chip tone={b.status === "at_risk" ? "vermilion" : "emerald"} icon="clock">{b.daysLeft} days left · best before {b.bestBefore}</Chip><Chip>{num(b.cartons)} cartons · {num(b.packets)} packets</Chip><Chip icon="pin">{org.name} · {org.city}{b.shelf ? " · shelf " + b.shelf : ""}</Chip><StatusChip status={b.status} /></div></div>
        <Stages steps={["Verify", "Value", "Route", "Approve", "Execute", "Settle"]} now={stage} />
        <Tabs tabs={tabs} value={tab} onChange={t => nav("batches/" + id + "/" + t)} />
        <div className="detail">
          <div className="main-col">
            {tab === "overview" && <>
              <Plate className="labelcard"><div className="labelphoto">{b.photo.status === "verified" ? <><img className="real" src={CARTON} alt="Carton label photo" /><span className="ver"><Chip tone="emerald" solid icon="check">Verified · {b.photo.confidence || 0.97}</Chip></span></> : <><img className="plate-img" src={p.plate || IMG + "hero-carton.webp"} alt="" /><span className="ver"><Chip icon="camera">{b.photo.status === "requested" ? "photo requested " + ago(b.photo.at) : b.photo.status === "reading" ? "reading the label" : "no label photo yet"}</Chip></span></>}</div>
                <div className="stack-sm"><h3>The batch</h3><KV items={[["Product", p.name], ["SKU · HSN", p.sku + " · " + p.hsn], ["Manufactured", b.mfg || "—"], ["Best before", b.bestBefore], ["MRP", inr(p.mrp) + " · " + p.perCarton + " a carton"], ["Distributor cost", inr(p.cost) + " a packet"], ["Sell-through", b.sellPerDay + " packets a day"], ["Will sell by date", num(Math.min(b.packets, b.sellPerDay * Math.max(0, b.daysLeft - 7))) + " of " + num(b.packets)]]} /></div></Plate>
              <div className="exec">
                <Plate className="stack-sm"><h3>Delivery-app gates</h3><div><Gate app="Blinkit" rule={"needs " + rules.gates.blinkit + " days"} ok={!!(b.gates && b.gates.blinkit)} /><Gate app="Zepto" rule={"needs " + Math.round(p.life * rules.gates.zepto) + " days"} ok={!!(b.gates && b.gates.zepto)} /><Gate app="Instamart" rule={"needs " + Math.round(p.life * rules.gates.instamart) + " days"} ok={!!(b.gates && b.gates.instamart)} /></div></Plate>
                <Plate className="stack-sm"><h3>If nothing is done</h3><div className="ledger"><div className="lrow neg"><span>Stock at cost<small>{num(b.packets)} × {inr(p.cost)}</small></span><span className="v">− {inr(b.packets * p.cost)}</span></div><div className="lrow neg"><span>GST credit paid back<small>s.17(5)(h), indicative</small></span><span className="v">− {inr(Math.round(b.packets * p.cost * p.gst / 100))}</span></div><div className="lrow neg"><span>Disposal and EPR</span><span className="v">− {inr(Math.round(b.cartons * 42))}</span></div><div className="lrow sum"><span>The bin costs</span><span className="v" style={{ color: "var(--vermilion-text)" }}>− {inr(b.binCost || Math.round(b.packets * p.cost * 1.27))}</span></div></div></Plate>
                <Plate className="stack-sm"><h3>Notes</h3><p className="t-small muted">{b.note || "No notes on this batch."}</p><Field id="note"><Input id="note" placeholder="Add a note for the team" value={note} onChange={e => setNote(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && note.trim()) { DB.update("batches", id, { note: note.trim() }); DB.audit(user.id, "added note", id); setNote(""); } }} /></Field></Plate>
              </div>
            </>}
            {tab === "verification" && <Plate className="labelcard">
              <div className="labelphoto">{b.photo.status === "verified" ? <><img className="real" src={CARTON} alt="Carton label photo from the shelf" /><span className="ver"><Chip tone="emerald" solid icon="check">Verified · Gemini vision · {b.photo.confidence || 0.97}</Chip></span></> : b.photo.status === "reading" ? <><img className="real" src={CARTON} alt="" style={{ opacity: .6 }} /><span className="ver"><Chip tone="chrome" icon="clock">Gemini is reading the label</Chip></span></> : <><img className="plate-img" src={p.plate || IMG + "hero-carton.webp"} alt="" /><span className="ver"><Chip icon="camera">{b.photo.status === "requested" ? "waiting for the distributor · asked " + ago(b.photo.at) : "no label photo yet"}</Chip></span></>}</div>
              <div className="stack-sm"><h3>Label, read from the shelf</h3>
                {b.photo.status === "verified" ? <><KV items={[["Batch", b.id], ["Manufactured", b.mfg || "—"], ["Best before", b.bestBefore], ["MRP", inr(p.mrp) + " · " + p.perCarton + " × " + p.name.split(" ").slice(-2).join(" ")], ["Pack", "sealed, dry"], ["Records", "match"], ["Read at", when(b.photo.at)]]} />{plan ? <Btn icon="arrow" onClick={() => nav("batches/" + id + "/plan")}>Open the plan</Btn> : canOperate && b.status !== "cleared" && <Btn kind="primary" icon="spark" onClick={() => Bus.publish("photo.verified", { batch: id })}>Price the six doors</Btn>}</>
                : b.photo.status === "requested" ? <><p className="t-small muted">Push sent to {org.name} {ago(b.photo.at)}. Warehouse records are often a week old, so the agent waits for the label before pricing anything.</p><div className="row wrap"><Btn kind="ghost" icon="refresh" onClick={() => Bus.publish("photo.requested", { batch: id, by: user.id })}>Send again</Btn>{canOperate && <Btn kind="ghost" icon="edit" onClick={() => setManual(true)}>Enter by hand</Btn>}</div></>
                : b.photo.status === "reading" ? <p className="t-small muted">Reading the batch code, both dates and the MRP straight off the pack.</p>
                : <><p className="t-small muted">The agent prices nothing until a person photographs one carton label on the shelf and Gemini reads it.</p>{canOperate && <div className="row wrap"><Btn kind="primary" icon="camera" onClick={() => Bus.publish("photo.requested", { batch: id, by: user.id })}>Ask {org.name} for one photo</Btn><Btn kind="ghost" icon="edit" onClick={() => setManual(true)}>Enter by hand</Btn></div>}</>}
              </div>
            </Plate>}
            {tab === "plan" && (!plan ? <Plate><Empty icon="scale" title="No plan yet" body={b.photo.status === "verified" ? "The label is verified. Price the doors to get a plan." : "A plan appears once the label photo is verified."} action={b.photo.status === "verified" && canOperate ? <Btn kind="primary" icon="spark" onClick={() => Bus.publish("photo.verified", { batch: id })}>Price the six doors</Btn> : <Btn onClick={() => nav("batches/" + id + "/verification")}>Go to verification</Btn>} /></Plate> : <>
              <div className="stack-sm"><div className="row between wrap"><h3>Six doors, per carton of {p.perCarton}, after costs</h3><Chip mono>Valuer · {when(plan.at)}</Chip></div><div className="doors stagger">{plan.doors.map(d => <Door key={d.id} door={Object.assign({}, DOOR_META[d.id], d)} selected={!!d.pick} />)}</div></div>
              <Plate className="stack"><div className="row between wrap"><h3>Recommended split</h3><StatusChip status={plan.status} /></div>
                <Tape total={1360} capLabel="pkts" segments={[{ id: "shops", label: "shops " + plan.split.shops.packets, value: plan.split.shops.packets }, { id: "online", label: "online " + plan.split.online.packets, value: plan.split.online.packets }]} />
                <div className="ledger"><div className="lrow pos"><span>{plan.split.shops.packets} packets · {plan.split.shops.cartons} cartons → 14 kirana shops at ₹{plan.split.shops.price}<small>buy 10 get 2 · 48-hour scheme in Hindi</small></span><span className="v">{inr(plan.split.shops.gross)}</span></div><div className="lrow pos"><span>{plan.split.online.packets} packets · {plan.split.online.cartons} cartons → ExpireSoon at ₹{plan.split.online.price}<small>floor ₹{plan.split.online.floor}</small></span><span className="v">{inr(plan.split.online.gross)}</span></div><div className="lrow neg"><span>Van delivery and listing fee</span><span className="v">− {inr(plan.split.costs)}</span></div><div className="lrow sum"><span>Net recovered · {plan.split.pctMrp}% of MRP</span><span className="v">{inr(plan.net)}</span></div><div className="lrow neg"><span>If binned instead</span><span className="v">− {inr(plan.bin)}</span></div><div className="lrow pos"><span>GST input credit stays safe <span className="t-xs muted">(indicative)</span></span><span className="v">{inr(plan.itc)}</span></div></div>
                {plan.status === "approved" && <div className="row wrap"><Avatar person={{ name: "", img: (DB.user(plan.approvedBy) || {}).avatar }} size="md" /><div><b>Approved by {(DB.user(plan.approvedBy) || {}).name} · {when(plan.approvedAt)}</b><div className="t-small muted">Logged with who, when and device.</div></div><Chip tone="chrome" solid className="stamp">APPROVED</Chip></div>}
                {plan.status === "rejected" && <Plate tone="vermilion-soft" tight><b style={{ color: "var(--vermilion-text)" }}>Rejected by {(DB.user(plan.rejectedBy) || {}).name}</b><div className="t-small">{plan.reason}</div></Plate>}
              </Plate>
              {plan.status === "awaiting_approval" && canOperate && <div className="approvebar"><Plate lift><div className="inner"><div className="nums"><div>You get<b>{inr(plan.net)}</b></div><div>Instead of<b style={{ color: "var(--vermilion-text)" }}>− {inr(plan.bin)}</b></div><div>GST credit safe<b style={{ color: "var(--emerald-text)" }}>{inr(plan.itc)}</b></div></div><Btn kind="ghost" onClick={() => setReject(true)}>Reject</Btn><Btn kind="yes" size="lg" icon="check" onClick={() => setApprove(true)}>Review and approve</Btn></div></Plate></div>}
            </>)}
            {tab === "execution" && (stage < 4 ? <Plate><Empty icon="spark" title="Nothing executing yet" body="Listing, outreach and negotiation start the moment a plan is approved." /></Plate> : <div className="exec">
              <Plate className="stack-sm"><div className="row between"><h3>Lister · ExpireSoon</h3>{listing ? <Chip tone="violet" solid>{listing.status}</Chip> : <Chip>queued</Chip>}</div>{listing ? <><div className="code scroll">{`POST /v1/listings\n{ "sku": "${p.sku}", "batch": "${id}",\n  "qty": ${listing.qty}, "price": ${listing.price}.00, "floor": ${listing.floor}.00 }\n\n201 { "id": "${listing.id}", "status": "${listing.status}" }`}</div><KV items={[["Listing", listing.id], ["Price · floor", inr(listing.price) + " · " + inr(listing.floor)], listing.awardedPrice && ["Awarded at", inrDec(listing.awardedPrice)], ["Bids", String(DB.list("bids", { where: { listing: listing.id } }).length)]]} /></> : <Skeleton h={80} />}</Plate>
              <Plate className="stack-sm"><div className="row between"><h3>Outreach · {offer ? offer.shopsNotified : 38} shops</h3><Chip tone="ultra" solid icon="bell">push · Hindi</Chip></div>{offer && <Plate tone="chrome-soft" tight><p className="hi" style={{ fontSize: 15 }}>{offer.textHindi}</p></Plate>}<div className="g38">{Array.from({ length: 38 }).map((_, i) => <b key={i} className={i < orders.filter(o => o.type === "shop").length ? "lit" : ""} />)}</div><div className="tilerow"><LiveTile value={orders.filter(o => o.type === "shop").length} label="shops ordered" tone="emerald" /><LiveTile value={num(orders.filter(o => o.type === "shop").reduce((t, o) => t + o.qty, 0))} label="packets" /></div><Btn size="sm" icon="store" onClick={() => nav("orders")}>All orders</Btn></Plate>
              <Plate className="stack-sm"><div className="row between"><h3>Negotiator</h3>{listing && listing.status === "awarded" ? <Chip tone="emerald" solid>awarded · {inrDec(listing.awardedPrice)}</Chip> : <Chip>floor hidden</Chip>}</div>{listing ? <div className="chat">{DB.list("bids", { where: { listing: listing.id }, sort: ["at", "asc"] }).map(bd => <React.Fragment key={bd.id}><div className="msg me"><Avatar person={{ name: "buyer", img: (DB.user((DB.org(bd.by) || {}).contact) || {}).avatar }} size="md" /><div className="bub">{inrDec(bd.price)} a packet for all {listing.qty}?<small>{(DB.org(bd.by) || {}).name} · {when(bd.at)}</small></div></div>{bd.status !== "placed" && <div className="msg"><Mark size="sm" sun={false} /><div className="bub ag">{bd.status === "accepted" && !bd.counter ? "Accepted. Dispatch within 24 hours of the balance." : inrDec(bd.counter) + ", dispatch within 24 hours of the balance."}<small>Negotiator agent as {org.name}</small></div></div>}{bd.status === "accepted" && <Chip tone="emerald" icon="check">Token received · balance before dispatch</Chip>}</React.Fragment>)}{!DB.list("bids", { where: { listing: listing.id } }).length && <div className="empty t-small" style={{ padding: "12px 6px" }}>Waiting for a bid. The agent counters anything under the floor.</div>}</div> : <Skeleton h={60} />}</Plate>
            </div>)}
            {tab === "documents" && (!docs.length ? <Plate><Empty icon="file" title="No documents yet" body="The Paperwork agent drafts the pack once the cartons have left the godown." /></Plate> : <div className="docs stagger">{docs.map(d => <button type="button" key={d.id} className={cx("doc", d.status === "not_required" && "na")} onClick={() => nav("documents/" + encodeURIComponent(d.id))}><div className="dh"><span>{d.title.toUpperCase()}</span><span className="mono" style={{ letterSpacing: 0, fontSize: 11 }}>{d.id}</span></div><div className="db"><div className="dl">{b.id} · {p.name}</div><div className="dt">{d.total ? inr(d.total) : (A.STATUS[d.status] || [0, d.status])[1]}</div><StatusChip status={d.status} /></div><div className="df">Open</div></button>)}</div>)}
            {tab === "timeline" && <Plate><h3>What happened, to the clock</h3>{tl.length ? <Timeline items={tl} scale={0.02} cap={56} /> : <p className="t-small muted">Nothing yet.</p>}</Plate>}
          </div>
          <aside className="aside">
            <Plate className="stack-sm"><h3>Money</h3><div className="ledger">{ledger ? <><div className="lrow pos"><span>Recovered</span><span className="v">{inr(ledger.recovered)}</span></div><div className="lrow pos"><span>GST credit kept</span><span className="v">{inr(ledger.itc)}</span></div><div className="lrow"><span>Kept out of landfill</span><span className="v">{ledger.kg} kg</span></div></> : plan ? <><div className="lrow pos"><span>Planned net</span><span className="v">{inr(plan.net)}</span></div><div className="lrow neg"><span>Bin avoided</span><span className="v">{inr(plan.bin)}</span></div></> : <><div className="lrow neg"><span>At stake if binned</span><span className="v">{inr(b.binCost || 0)}</span></div><div className="lrow"><span>Packets at risk</span><span className="v">{num(Math.round(b.atRisk || 0))}</span></div></>}</div></Plate>
            <Plate className="stack-sm"><h3>People</h3><Who user={(org.contact)} sub={org.name} />{plan && plan.approvedBy && <Who user={plan.approvedBy} sub="approved the plan" />}</Plate>
            <Plate className="stack-sm"><h3>Orders</h3>{orders.length ? orders.slice(0, 5).map(o => <div key={o.id} className="row between t-small"><span>{o.party.split(" · ")[0]}</span><b className="mono">{num(o.qty)}</b></div>) : <p className="t-small muted">None yet.</p>}</Plate>
          </aside>
        </div>
      </div>
      <ConfirmSheet open={approve} onClose={() => setApprove(false)} title="Approve the plan" confirmLabel={"Approve · release the agents"} onConfirm={async () => { await new Promise(r => setTimeout(r, 700)); Bus.publish("plan.approved", { batch: id, plan: plan && plan.id, by: user.id }); }}>
        {plan && <><div className="ledger"><div className="lrow pos"><span>You get</span><span className="v" style={{ fontSize: 22 }}>{inr(plan.net)}</span></div><div className="lrow neg"><span>Instead of losing</span><span className="v" style={{ fontSize: 22 }}>− {inr(plan.bin)}</span></div><div className="lrow pos"><span>GST credit stays safe</span><span className="v" style={{ fontSize: 22 }}>{inr(plan.itc)}</span></div></div><h4>What happens the moment you tap</h4><div className="stack-sm t-small"><div className="row top"><Icon name="tag" size={18} /><span>Lister posts 772 packets on ExpireSoon at ₹15, floor ₹14, with the label photo and dates.</span></div><div className="row top"><Icon name="send" size={18} /><span>Outreach pushes the Hindi scheme to 38 shops: 588 packets at ₹18, buy 10 get 2, 48 hours.</span></div><div className="row top"><Icon name="shield" size={18} /><span>Nothing is listed, messaged or shipped before this tap. Approval is logged with who, when and device.</span></div></div></>}
      </ConfirmSheet>
      <FormSheet open={reject} onClose={() => setReject(false)} title="Reject the plan" submitLabel="Reject" valid={reason.trim().length > 3} onSubmit={async () => { Bus.publish("plan.rejected", { batch: id, plan: plan && plan.id, by: user.id, reason }); setReason(""); }}><Field label="Why" help="The Router learns from the reason." id="why"><textarea id="why" className="textarea" value={reason} onChange={e => setReason(e.target.value)} placeholder="e.g. hold 10 cartons for the Diwali staff sale" /></Field></FormSheet>
      <ConfirmSheet open={writeoff} onClose={() => setWriteoff(false)} title={"Write off " + id + "?"} body={"Every exit is refused and the stock goes to disposal. This costs about " + inr(b.binCost || Math.round(b.packets * p.cost * 1.27)) + " including the GST credit reversal and EPR charge."} confirmLabel="Write off" danger onConfirm={async () => { DB.update("batches", id, { status: "written_off", closedAt: new Date().toISOString() }); DB.audit(user.id, "wrote off", id); }} />
      <FormSheet open={manual} onClose={() => setManual(false)} title="Enter the label by hand" submitLabel="Mark verified" onSubmit={async () => { DB.update("batches", id, { photo: { status: "verified", at: new Date().toISOString(), confidence: 1, manual: true, by: user.id } }); DB.audit(user.id, "entered label by hand", id); Bus.publish("photo.verified", { batch: id }); }}><Field label="Batch code" id="mb"><Input id="mb" mono defaultValue={b.id} /></Field><Field label="Best before" id="mbb"><Input id="mbb" defaultValue={b.bestBefore} /></Field><Field label="MRP" id="mm"><Input id="mm" mono defaultValue={"₹" + p.mrp + ".00"} /></Field><p className="t-xs muted">Manual entries are flagged in the audit log; the photo is still the preferred source of truth.</p></FormSheet>
    </>;
  }
  const AGENT_OF = { "batch.flagged": "Watcher", "photo.requested": "Vision", "photo.verified": "Vision", "plan.ready": "Router", "plan.approved": "", "listing.posted": "Lister", "offer.pushed": "Outreach", "order.placed": "Outreach", "bid.placed": "Negotiator", "bid.countered": "Negotiator", "bid.accepted": "Negotiator", "shipment.dispatched": "", "documents.ready": "Paperwork", "ledger.closed": "Impact", "watcher.run": "Watcher" };
  const EVENT_TEXT = { "watcher.run": "checked every batch against the gates and sell-through", "batch.flagged": "flagged the batch: fails the app gates and will not sell out", "photo.requested": "asked the distributor for one label photo", "photo.sent": "photo received from the shelf", "photo.verified": "read the label: batch, dates and MRP match", "plan.ready": "priced six doors and proposed the split", "plan.approved": "plan approved", "plan.rejected": "plan rejected", "listing.posted": "listing posted on ExpireSoon", "offer.pushed": "Hindi scheme pushed to the shop cluster", "order.placed": "a shop ordered", "bid.placed": "a bid came in", "bid.countered": "countered the bid", "bid.accepted": "bid accepted, token paid", "shipment.started": "the van round started", "shipment.dispatched": "cartons dispatched", "documents.ready": "document pack issued", "ledger.closed": "ledger closed, BRSR row written" };

  /* ---------- Approvals, Orders, Partners, Reports ---------- */
  function Approvals({ user, nav }) {
    const v = useDB(); const rows = DB.list("plans", { sort: ["at", "desc"] }).map(pl => ({ ...pl, batchDoc: DB.get("batches", pl.batch) })).filter(r => r.batchDoc);
    return <><TopBar title="Approvals" unread={DB.list("notifications", { where: { user: user.id, read: false } }).length} onBell={() => nav("notifications")}><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} /></TopBar>
      <div className="page"><PageHead title="Approvals" sub="One tap releases the agents. Nothing is listed, messaged or shipped before it." />
        <DataTable rows={rows} onRow={r => nav("batches/" + r.batch + "/plan")} empty={<Empty icon="check" title="Nothing waiting for a yes" body="Plans appear here when a label is verified and the doors are priced." />} columns={[{ key: "batch", label: "Batch", render: r => <span className="cellwho"><span><b className="mono">{r.batch}</b><span>{(DB.product(r.batchDoc.product) || {}).name}</span></span></span> }, { key: "net", label: "You get", n: true, render: r => inr(r.net) }, { key: "bin", label: "Instead of", n: true, render: r => <span style={{ color: "var(--vermilion-text)" }}>− {inr(r.bin)}</span> }, { key: "status", label: "Status", render: r => <StatusChip status={r.status} /> }, { key: "at", label: "Proposed", render: r => <span className="t-xs muted mono">{ago(r.at)}</span> }, { key: "x", label: "", sortable: false, render: r => r.status === "awaiting_approval" ? <Btn kind="yes" size="sm" icon="check" onClick={() => nav("batches/" + r.batch + "/plan")}>Review</Btn> : null }]} /></div></>;
  }
  function Orders({ user, nav, scope }) {
    const v = useDB(); const [q, setQ] = useState(""); const [type, setType] = useState("all"); const [sort, setSort] = useState(["at", "desc"]);
    let rows = DB.list("orders", { search: q }); if (scope) rows = rows.filter(scope); if (type !== "all") rows = rows.filter(o => o.type === type);
    return <><TopBar title="Orders" unread={DB.list("notifications", { where: { user: user.id, read: false } }).length} onBell={() => nav("notifications")}><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} /></TopBar>
      <div className="page"><PageHead title="Orders" sub="Shop orders from the schemes, marketplace awards, staff sales and donations." actions={<Btn icon="download" onClick={() => exportCSV(rows.map(o => ({ id: o.id, type: o.type, batch: o.batch, party: o.party, qty: o.qty, price: o.price, status: o.status, at: o.at })), "orders.csv")}>Export</Btn>} />
        <Toolbar search={q} onSearch={setQ} placeholder="Order, batch, shop" count={rows.length}><Pills options={[{ id: "all", label: "All" }, { id: "shop", label: "Shops" }, { id: "online", label: "ExpireSoon" }, { id: "staff", label: "Staff" }, { id: "donation", label: "Donations" }]} value={type} onChange={setType} /></Toolbar>
        <DataTable rows={rows} sort={sort} onSort={setSort} onRow={o => nav("batches/" + o.batch + "/execution")} columns={[{ key: "id", label: "Order", w: 110, render: o => <b className="mono">{o.id}</b> }, { key: "party", label: "Party" }, { key: "batch", label: "Batch", render: o => <span className="mono">{o.batch}</span> }, { key: "qty", label: "Packets", n: true, render: o => num(o.qty) }, { key: "price", label: "Rate", n: true, render: o => o.price ? inrDec(o.price) : "—" }, { key: "value", label: "Value", n: true, sortValue: o => o.qty * o.price, render: o => inr(o.qty * o.price) }, { key: "status", label: "Status", render: o => <StatusChip status={o.status} /> }, { key: "at", label: "When", render: o => <span className="t-xs muted mono">{ago(o.at)}</span> }]} /></div></>;
  }
  function Partners({ user, nav, id }) {
    const v = useDB(); const [q, setQ] = useState(""); const [kind, setKind] = useState("all"); const [invite, setInvite] = useState(false); const [f, setF] = useState({ name: "", kind: "distributor", city: "", contactName: "", phone: "" });
    const rows = DB.list("orgs", { search: q }).filter(o => kind === "all" || o.kind === kind).map(o => ({ ...o, batches: DB.list("batches", { where: { org: o.id } }).length, people: DB.list("users", { where: { org: o.id } }).length }));
    const sel = id ? DB.org(id) : null;
    return <><TopBar title="Partners" back={sel ? "Partners" : undefined} onBack={() => nav("partners")} unread={DB.list("notifications", { where: { user: user.id, read: false } }).length} onBell={() => nav("notifications")}><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} /></TopBar>
      <div className="page">{sel ? <>
        <PageHead title={sel.name} sub={[sel.kind, sel.city, sel.gstin].filter(Boolean).join(" · ")} actions={<Btn icon="users" onClick={() => setInvite(true)}>Invite a person</Btn>} />
        <div className="detail"><div className="main-col">
          <Plate className="stack-sm"><h3>People</h3>{DB.list("users", { where: { org: sel.id } }).map(u => <div key={u.id} className="row between"><Who user={u} /><div className="row"><A.RoleChip role={u.role} /><StatusChip status={u.status} /></div></div>)}</Plate>
          <Plate className="stack-sm"><h3>Batches here</h3><DataTable rows={DB.list("batches", { where: { org: sel.id }, sort: ["daysLeft", "asc"] })} onRow={b => nav("batches/" + b.id)} columns={[{ key: "id", label: "Batch", render: b => <span className="mono">{b.id}</span> }, { key: "product", label: "Product", render: b => (DB.product(b.product) || {}).name }, { key: "daysLeft", label: "Days", n: true }, { key: "cartons", label: "Cartons", n: true }, { key: "status", label: "Status", render: b => <StatusChip status={b.status} /> }]} empty={<Empty icon="box" title="No batches here" />} /></Plate>
        </div><aside className="aside"><Plate className="stack-sm"><h3>Details</h3><KV items={[["Kind", sel.kind], ["City", sel.city], sel.godown && ["Godown", sel.godown], sel.pincodes && ["Pincodes", sel.pincodes.join(", ")], sel.cluster && ["Cluster", sel.cluster], sel.gstin && ["GSTIN", sel.gstin], ["Since", DB.fmtDate(new Date(sel.since))]]} /></Plate></aside></div>
      </> : <>
        <PageHead title="Partners" sub="Distributors, retailer clusters, marketplace buyers and food banks." actions={<Btn kind="primary" icon="plus" onClick={() => setInvite(true)}>Add a partner</Btn>} />
        <Toolbar search={q} onSearch={setQ} placeholder="Name, city, GSTIN" count={rows.length}><Pills options={[{ id: "all", label: "All" }, { id: "distributor", label: "Distributors" }, { id: "retailer", label: "Retailers" }, { id: "buyer", label: "Buyers" }, { id: "foodbank", label: "Food banks" }]} value={kind} onChange={setKind} /></Toolbar>
        <DataTable rows={rows} onRow={o => nav("partners/" + o.id)} columns={[{ key: "name", label: "Partner", render: o => <b>{o.name}</b> }, { key: "kind", label: "Kind", render: o => <Chip tone={{ distributor: "kraft", retailer: "vermilion", buyer: "violet", foodbank: "emerald", brand: "ultra" }[o.kind]}>{o.kind}</Chip> }, { key: "city", label: "City" }, { key: "contact", label: "Contact", render: o => <Who user={o.contact} /> }, { key: "batches", label: "Batches", n: true }, { key: "people", label: "People", n: true }, { key: "since", label: "Since", render: o => <span className="t-xs muted mono">{ago(o.since)}</span> }]} />
      </>}</div>
      <FormSheet open={invite} onClose={() => setInvite(false)} title={sel ? "Invite a person to " + sel.name : "Add a partner"} submitLabel={sel ? "Send invite" : "Add and invite"} valid={sel ? !!(f.contactName && f.phone) : !!(f.name && f.city && f.contactName && f.phone)} onSubmit={async () => { let orgId = sel ? sel.id : DB.insert("orgs", { name: f.name, kind: f.kind, city: f.city, since: new Date().toISOString() }).id; const role = { distributor: "distributor", retailer: "retailer", buyer: "buyer", foodbank: "foodbank" }[sel ? sel.kind : f.kind] || "distributor"; const u = DB.insert("users", { name: f.contactName, phone: f.phone, email: "", role, org: orgId, status: "invited", title: "Owner", provider: "phone", avatar: null, createdAt: new Date().toISOString() }); if (!sel) DB.update("orgs", orgId, { contact: u.id }); DB.audit(user.id, "invited user", u.id); Bus.publish("user.invited", { user: u.id, by: user.id }); setF({ name: "", kind: "distributor", city: "", contactName: "", phone: "" }); }}>
        {!sel && <><Field label="Partner name" id="pn"><Input id="pn" value={f.name} onChange={e => setF({ ...f, name: e.target.value })} placeholder="Sri Sai Distributors" /></Field><Field label="Kind" id="pk"><Select id="pk" value={f.kind} onChange={e => setF({ ...f, kind: e.target.value })}><option value="distributor">Distributor</option><option value="retailer">Retailer</option><option value="buyer">Marketplace buyer</option><option value="foodbank">Food bank</option></Select></Field><Field label="City" id="pc"><Input id="pc" value={f.city} onChange={e => setF({ ...f, city: e.target.value })} /></Field></>}
        <Field label="Contact name" id="cn"><Input id="cn" value={f.contactName} onChange={e => setF({ ...f, contactName: e.target.value })} /></Field>
        <Field label="Mobile number" help="They sign in with a one-time code on this number." id="cp"><Input id="cp" mono inputMode="tel" value={f.phone} onChange={e => setF({ ...f, phone: e.target.value })} placeholder="+91 98XXX XXXXX" /></Field>
      </FormSheet></>;
  }
  function Reports({ user, nav }) {
    const v = useDB(); const led = DB.list("ledger", { sort: ["closedAt", "desc"] });
    const tot = led.reduce((t, l) => ({ recovered: t.recovered + l.recovered, itc: t.itc + l.itc, kg: t.kg + l.kg, meals: t.meals + l.meals }), { recovered: 0, itc: 0, kg: 0, meals: 0 });
    return <><TopBar title="Reports" unread={DB.list("notifications", { where: { user: user.id, read: false } }).length} onBell={() => nav("notifications")}><A.UserMenu user={user} onProfile={() => nav("profile")} onSignOut={() => Auth.signOut()} /></TopBar>
      <div className="page"><PageHead title="Reports" sub="Every rupee, credit and kilo in one ledger that finance and sustainability both read." actions={<Btn icon="download" onClick={() => exportCSV(led.map(l => ({ batch: l.batch, recovered: l.recovered, itc: l.itc, kg: l.kg, co2: l.co2, meals: l.meals, closed: l.closedAt })), "ledger.csv")}>Export ledger</Btn>} />
        <div className="tilerow"><LiveTile value={inr(tot.recovered)} label="recovered" tone="emerald" /><LiveTile value={inr(tot.itc)} label="GST credit kept" /><LiveTile value={Math.round(tot.kg) + " kg"} label="out of landfill" tone="ultra" /><LiveTile value={num(tot.meals)} label="meals" /></div>
        <DataTable rows={led} onRow={l => nav("batches/" + l.batch)} columns={[{ key: "batch", label: "Batch", render: l => <b className="mono">{l.batch}</b> }, { key: "recovered", label: "Recovered", n: true, render: l => inr(l.recovered) }, { key: "writeoffAvoided", label: "Write-off avoided", n: true, render: l => inr(l.writeoffAvoided) }, { key: "itc", label: "ITC kept", n: true, render: l => inr(l.itc) }, { key: "kg", label: "kg", n: true }, { key: "co2", label: "tCO₂e", n: true }, { key: "closedAt", label: "Closed", render: l => <span className="t-xs muted mono">{l.closedAt ? ago(l.closedAt) : "open"}</span> }]} /></div></>;
  }

  window.SC_APP = Object.assign(window.SC_APP, { Today, Batches, BatchDetail, Approvals, Orders, Partners, Reports, exportCSV, labelState, toLabel, DOOR_META, CARTON });
})();
