// Builds core's icon registry from the design system's own icon list. design3/system/icons.js names every icon the
// product uses (its paths come from lucide-static 0.468); the registry keeps those names and takes each icon's current
// path data from @lucide/svelte, so <Icon name="…"> works exactly as SC3.Icon does. An icon Lucide does not have (the
// Google mark) keeps the prototype's own drawing.
//   node scripts/icons.mjs           write core/src/lib/icons/registry.ts
//   node scripts/icons.mjs --check   fail if the registry is out of date with design3 or the installed Lucide
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, realpathSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const source = join(root, '../design3/system/icons.js');
const out = join(root, 'core/src/lib/icons/registry.ts');
// @lucide/svelte exports no package.json, so read it where pnpm linked it for core
const lucide = realpathSync(join(root, 'core/node_modules/@lucide/svelte'));
const lucideVersion = JSON.parse(readFileSync(join(lucide, 'package.json'), 'utf8')).version;

// the prototype's icon set, run as the browser would
const text = readFileSync(source, 'utf8');
const sandbox = { window: {} };
vm.runInNewContext(text, sandbox, { filename: source });
const prototype = sandbox.window.SC3_ICONS;
const names = Object.keys(prototype);

// <path d="…" /> <circle cx="…" … /> → [["path", { d: "…" }], ["circle", { … }]]
function parseSvg(inner) {
	const nodes = [];
	for (const [, tag, attrs] of inner.matchAll(/<([a-z]+)\s+([^>]*?)\s*\/?>/g)) {
		const a = {};
		for (const [, k, v] of attrs.matchAll(/([a-zA-Z-:]+)="([^"]*)"/g)) a[k] = v;
		nodes.push([tag, a]);
	}
	return nodes;
}

// the icon's own file, or, for a name Lucide has since renamed (trash-2 is now trash), the file its alias points to
function lucideFile(name) {
	const dir = join(lucide, 'dist/icons');
	if (existsSync(join(dir, name + '.svelte'))) return join(dir, name + '.svelte');
	const alias =
		existsSync(join(dir, name + '.js')) &&
		readFileSync(join(dir, name + '.js'), 'utf8').match(/from "\.\/([a-z0-9-]+)\.svelte"/);
	return alias ? join(dir, alias[1] + '.svelte') : null;
}

const icons = {};
const custom = [];
for (const name of names) {
	const file = lucideFile(name);
	if (file) {
		const m = readFileSync(file, 'utf8').match(/const iconData = (\{.*\});/);
		if (!m) throw new Error(`cannot read the icon data in ${file}`);
		icons[name] = JSON.parse(m[1]).node;
	} else {
		icons[name] = parseSvg(prototype[name]);
		custom.push(name);
	}
}

const hash = createHash('sha256').update(text).digest('hex').slice(0, 16);
// kept in design3's order, so a page that lists them (the design system page's icon grid) lists them as the prototype does
const body = names.map((n) => `\t${JSON.stringify(n)}: ${JSON.stringify(icons[n])}`).join(',\n');
const generated = `// Generated by scripts/icons.mjs: do not edit. Run \`corepack pnpm icons\` after design3/system/icons.js changes.
// ${names.length} icons named by design3/system/icons.js (sha256 ${hash}), drawn from @lucide/svelte ${lucideVersion};
// ${custom.length ? custom.join(', ') + ' kept from the prototype, since Lucide does not draw it' : 'every one from Lucide'}.
export type IconNode = [tag: string, attrs: Record<string, string>][];

export const ICONS = {
${body}
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;
`;

if (process.argv.includes('--check')) {
	const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
	if (current !== generated) {
		console.error('icons: core/src/lib/icons/registry.ts is out of date. Run `corepack pnpm icons`.');
		process.exit(1);
	}
	console.log(`icons: ${names.length} icons, up to date`);
} else {
	writeFileSync(out, generated);
	console.log(
		`icons: wrote ${names.length} icons (${custom.length} kept from the prototype: ${custom.join(', ') || 'none'})`
	);
}
