(function() {
  const K = window.SC3, D = window.SC3_DATA, M = window.SC3_MONEY;
  const fmt = M.fmt;
  const { cx, Icon, Badge, Button, Card, List, ListRow, ThemeProvider, AppRoot } = K;
  const q = new URLSearchParams(location.search);
  const OPT = q.get("opt") || "a", POLICY = q.get("policy") || "full-credit", SIDE = q.get("side") || "both";
  const hero = D.BATCHES.find((b) => b.hero), sku = D.SKUS[hero.sku], dist = D.DISTRIBUTORS[hero.distributor];
  const plan = D.PLAN, kl = plan.lines.find((l) => l.id === "kirana");
  const real = M.realised(plan, sku, { kirana: 24, expiresoon: kl ? plan.lines.find((l) => l.id === "expiresoon").units : 0 });
  const net = M.actualNet(real, D.COUNTER.price).net;
  const left = real.godown;
  const S = M.expirySettlement(left, sku, POLICY);
  const client = D.CLIENT.short, godown = dist.godown;
  const whose = (n) => n + (/s$/.test(n) ? "'" : "'s");
  const POLICY_NAME = { "full-credit": "Full credit at expiry", "price-support": "Price support only", none: "No returns" };
  const PAPER = { "full-credit": "Expiry credit note", "price-support": "Price support at expiry", none: "Expiry notice" };
  const rows = plan.lines.filter((l) => l.id !== "writeoff").map((l) => [l.short, l.units - (real.lines.find((x) => x.id === l.id) || { units: 0 }).units]).filter(([, n]) => n > 0);
  const sentence = POLICY === "full-credit" ? `The ${fmt.num(left)} packs come back to ${client} for full credit (${fmt.inr(S.credit)}), and ${client} destroys them.` : POLICY === "price-support" ? `The ${fmt.num(left)} packs stay with ${dist.name}, which destroys them; ${client} pays it the gap to its price (${fmt.inr(S.credit)}).` : `With no returns, the ${fmt.num(left)} packs are ${whose(dist.name)} loss, and it destroys them.`;
  const Line = ({ k, v, strong, sub }) => /* @__PURE__ */ React.createElement("div", { className: "pp-line" }, /* @__PURE__ */ React.createElement("span", null, k, sub && /* @__PURE__ */ React.createElement("em", null, " ", sub)), /* @__PURE__ */ React.createElement("span", { className: strong ? "pp-strong" : "" }, v));
  function Paper() {
    const head = (title, no, right) => /* @__PURE__ */ React.createElement("div", { className: "pp-head" }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { className: "pp-title" }, title), /* @__PURE__ */ React.createElement("div", { className: "pp-no" }, no)), right);
    if (POLICY === "none") return /* @__PURE__ */ React.createElement("div", { className: "paper pp" }, head(PAPER.none, `${hero.id} · ${dist.name}`, /* @__PURE__ */ React.createElement("span", { className: "pp-stamp" }, "NO RETURNS")), /* @__PURE__ */ React.createElement(Line, { k: `Packs expired at ${godown}`, v: fmt.num(left), strong: true }), /* @__PURE__ */ React.createElement(Line, { k: `Credit from ${client}`, v: "none" }), /* @__PURE__ */ React.createElement("p", { className: "pp-note" }, client, "'s expiry policy takes no returns: the packs no channel took are ", whose(dist.name), " loss, and it destroys them under its own records."));
    return /* @__PURE__ */ React.createElement("div", { className: "paper pp" }, head(PAPER[POLICY], `CN/0118 · ${client} → ${dist.name}`, /* @__PURE__ */ React.createElement("span", { className: "pp-stamp ok" }, "NO GST ADJ.")), /* @__PURE__ */ React.createElement(Line, { k: `${fmt.num(left)} packs expired at ${godown}`, sub: `at the ₹${sku.dp} dealer price`, v: fmt.inr2(S.credit) }), /* @__PURE__ */ React.createElement(Line, { k: `Credit to ${dist.name}`, v: fmt.inr2(S.credit), strong: true }), POLICY === "full-credit" ? /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", { className: "pp-sub" }, client, "'s own costs, on destroying them"), /* @__PURE__ */ React.createElement(Line, { k: "Disposal", sub: `${fmt.num(left)} × ₹${M.RULES.disposalPerUnit.toFixed(2)}`, v: fmt.inr2(S.disposal) }), /* @__PURE__ */ React.createElement(Line, { k: "EPR on the packaging", sub: fmt.kg(S.kg), v: fmt.inr2(S.epr) }), /* @__PURE__ */ React.createElement(Line, { k: "Input GST reversed", sub: "section 17(5)(h)", v: fmt.inr2(S.itc) }), /* @__PURE__ */ React.createElement(Line, { k: "Expiry, all in", v: fmt.inr2(S.total), strong: true })) : null, /* @__PURE__ */ React.createElement("p", { className: "pp-note" }, POLICY === "full-credit" ? `A financial credit note for the packs that came back on expiry day. ${client} destroys them; the destruction certificate counts them and the GST memo reverses their input credit.` : `${client}'s expiry policy is price support only: nothing comes back. ${dist.name} is paid the gap to the ₹${sku.dp} it paid, and destroys the packs itself.`));
  }
  const lineRows = () => /* @__PURE__ */ React.createElement(List, null, rows.map(([k, n]) => /* @__PURE__ */ React.createElement(ListRow, { key: k, title: k, sub: "planned, not taken", value: /* @__PURE__ */ React.createElement("span", { className: "tnum strong" }, fmt.num(n)) })));
  function OptionA() {
    return /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "row tight" }, /* @__PURE__ */ React.createElement("span", { className: "icontile gray", style: { borderRadius: 9 } }, /* @__PURE__ */ React.createElement(Icon, { name: "hourglass", size: 17, stroke: 2 })), /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "Expired at the godown")), /* @__PURE__ */ React.createElement(Badge, null, fmt.num(left), " packs")), lineRows(), /* @__PURE__ */ React.createElement("div", { className: "stack tight", style: { padding: "12px 14px", borderRadius: 14, background: "var(--fill)" } }, /* @__PURE__ */ React.createElement("div", { className: "row between t-subhead" }, /* @__PURE__ */ React.createElement("span", { className: "row tight" }, /* @__PURE__ */ React.createElement(Badge, { size: "sm", tone: POLICY === "none" ? void 0 : "green" }, POLICY_NAME[POLICY])), POLICY !== "none" && /* @__PURE__ */ React.createElement("span", { className: "tnum strong" }, fmt.inr(S.credit))), /* @__PURE__ */ React.createElement("span", { className: "t-footnote" }, sentence)), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, "Expiry day, by Report now. Net ", fmt.inr(net), " of the ", fmt.inr(plan.net), " planned; the figures count only what each channel took."), POLICY !== "none" && /* @__PURE__ */ React.createElement(Button, { variant: "outline", icon: "file-text" }, "Open the paper"));
  }
  function OptionB() {
    return /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 16 } }, /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "row tight" }, /* @__PURE__ */ React.createElement("span", { className: "icontile gray", style: { borderRadius: 9 } }, /* @__PURE__ */ React.createElement(Icon, { name: "warehouse", size: 17, stroke: 2 })), /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "Left at the godown")), /* @__PURE__ */ React.createElement(Badge, null, fmt.num(left), " packs")), lineRows()), /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "row tight" }, /* @__PURE__ */ React.createElement("span", { className: "icontile", style: { borderRadius: 9 } }, /* @__PURE__ */ React.createElement(Icon, { name: "hand-coins", size: 17, stroke: 2 })), /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "Expiry settlement")), /* @__PURE__ */ React.createElement(Badge, { tone: POLICY === "none" ? void 0 : "green", icon: "check" }, POLICY_NAME[POLICY])), /* @__PURE__ */ React.createElement("div", { style: { display: "grid", gap: 12, gridTemplateColumns: "repeat(3, minmax(0, 1fr))" } }, [["Credit to " + dist.short, POLICY === "none" ? "—" : fmt.inr(S.credit)], ["Destroyed by", S.destroyedBy === "client" ? client : dist.short], [POLICY === "full-credit" ? "Disposal, EPR, GST" : "Client's other costs", POLICY === "full-credit" ? fmt.inr(S.disposal + S.epr + S.itc) : "—"]].map(([k, v]) => /* @__PURE__ */ React.createElement("div", { key: k, className: "stack tight", style: { gap: 2, padding: "10px 12px", borderRadius: 12, background: "var(--fill)" } }, /* @__PURE__ */ React.createElement("span", { className: "t-caption subtle" }, k), /* @__PURE__ */ React.createElement("b", { className: "tnum" }, v)))), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, sentence), POLICY !== "none" && /* @__PURE__ */ React.createElement(Button, { variant: "outline", icon: "file-text" }, "Open the paper")));
  }
  function OptionC() {
    return /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "row tight" }, /* @__PURE__ */ React.createElement("span", { className: "icontile gray", style: { borderRadius: 9 } }, /* @__PURE__ */ React.createElement(Icon, { name: "warehouse", size: 17, stroke: 2 })), /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "Left at the godown")), /* @__PURE__ */ React.createElement(Badge, null, fmt.num(left), " packs")), lineRows(), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, "Expired on expiry day and settled in Paperwork: ", PAPER[POLICY].toLowerCase(), POLICY !== "none" ? `, ${fmt.inr(S.credit)} to ${dist.short}` : "", "."));
  }
  function Page() {
    const Card_ = { a: OptionA, b: OptionB, c: OptionC }[OPT];
    return /* @__PURE__ */ React.createElement("div", { className: cx("s94", SIDE) }, SIDE !== "paper" && /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 14 } }, /* @__PURE__ */ React.createElement("div", { className: "stack tight", style: { gap: 2 } }, /* @__PURE__ */ React.createElement("span", { className: "t-caption subtle" }, "Priya · Execution · ", hero.id), /* @__PURE__ */ React.createElement("span", { className: "t-title2" }, "Execution")), /* @__PURE__ */ React.createElement(Card_, null)), SIDE !== "ops" && /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 14 } }, /* @__PURE__ */ React.createElement("div", { className: "stack tight", style: { gap: 2 } }, /* @__PURE__ */ React.createElement("span", { className: "t-caption subtle" }, "Anita · Paperwork · ", hero.id), /* @__PURE__ */ React.createElement("span", { className: "t-title2" }, PAPER[POLICY])), /* @__PURE__ */ React.createElement(Paper, null)));
  }
  ReactDOM.createRoot(document.getElementById("root")).render(/* @__PURE__ */ React.createElement(ThemeProvider, null, /* @__PURE__ */ React.createElement(AppRoot, { scroll: "window" }, /* @__PURE__ */ React.createElement(Page, null))));
})();
