(function() {
  const { useState, useMemo, Fragment } = React;
  const { motion, AnimatePresence, useReducedMotion } = Motion;
  const K = window.SC3, D = window.SC3_DATA, M = window.SC3_MONEY, S = window.SC3_SCREENS, X = window.SC121;
  const { cx, Icon, Badge, Button, Card, List, ListRow, Segmented, Sheet, Product, Money, Roll, DocCard, useApp } = K;
  const { useRoute, Screen, Columns, SectionTitle } = S;
  const fmt = M.fmt;
  const r2 = (n) => Math.round(n * 100) / 100;
  const day = (iso) => (/* @__PURE__ */ new Date(iso + "T00:00:00")).toLocaleDateString("en-IN", { day: "numeric", month: "short" });
  const month = (iso) => (/* @__PURE__ */ new Date(iso + "T00:00:00")).toLocaleDateString("en-IN", { month: "long" });
  const inr2 = (n) => "₹" + n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const kg = (n) => fmt.kg(r2(n));
  function OutcomeBadge({ o, size }) {
    const x = X.OUTCOME[o];
    return /* @__PURE__ */ React.createElement(Badge, { size, tone: x.tone, icon: x.icon }, x.label);
  }
  function PeriodSwitch({ value, onChange }) {
    return /* @__PURE__ */ React.createElement(Segmented, { label: "Period", value, onChange, options: X.PERIODS.map((p) => ({ id: p.id, label: p.label })) });
  }
  const READINGS = [
    { id: "money", label: "Money", icon: "coins" },
    { id: "gst", label: "GST", icon: "badge-check" },
    { id: "impact", label: "Impact", icon: "leaf" }
  ];
  const valueOf = (b, reading) => reading === "money" ? b.ledger.net : reading === "gst" ? b.ledger.itcKept : b.ledger.kg;
  function ReadingSwitch({ value, onChange }) {
    return /* @__PURE__ */ React.createElement(Segmented, { label: "Reading", value, onChange, options: READINGS });
  }
  function Lakh({ value, size = "l" }) {
    return /* @__PURE__ */ React.createElement("span", { className: cx("num money", size) }, /* @__PURE__ */ React.createElement("span", { className: "sr-only" }, "₹" + (value / 1e5).toFixed(2) + " lakh"), /* @__PURE__ */ React.createElement("span", { className: "cur", "aria-hidden": "true" }, "₹"), /* @__PURE__ */ React.createElement(Roll, { value: value / 1e5, format: (v) => v.toFixed(2), hidden: true }), /* @__PURE__ */ React.createElement("span", { "aria-hidden": "true", className: "sc121-unit" }, "lakh"));
  }
  function Kilos({ value, size = "l" }) {
    const t = value >= 1e3;
    return /* @__PURE__ */ React.createElement("span", { className: cx("num", size) }, /* @__PURE__ */ React.createElement("span", { className: "sr-only" }, kg(value)), /* @__PURE__ */ React.createElement(Roll, { value: t ? value / 1e3 : value, format: (v) => t ? v.toFixed(2) : Math.round(v).toLocaleString("en-IN"), hidden: true }), /* @__PURE__ */ React.createElement("span", { "aria-hidden": "true", className: "sc121-unit" }, t ? "t" : "kg"));
  }
  function Headline({ t, reading, period }) {
    const p = X.PERIODS.find((x) => x.id === period);
    if (reading === "money") return /* @__PURE__ */ React.createElement("div", { className: "sc121-head" }, /* @__PURE__ */ React.createElement("div", { className: "sc121-fig" }, /* @__PURE__ */ React.createElement(Lakh, { value: t.net }), /* @__PURE__ */ React.createElement("span", { className: "sc121-what" }, "recovered")), /* @__PURE__ */ React.createElement("p", { className: "sc121-working" }, "From ", t.batches, " ", t.batches === 1 ? "batch" : "batches", " that would have cost ", fmt.lakh(t.writeOff), " to destroy: ", /* @__PURE__ */ React.createElement("b", null, fmt.lakh(t.swing)), " better than the bin, after ", fmt.lakh(t.support), " of price support to the distributors", t.credit ? ` and ${fmt.inr(t.credit)} of expiry credit` : "", "."));
    if (reading === "gst") return /* @__PURE__ */ React.createElement("div", { className: "sc121-head" }, /* @__PURE__ */ React.createElement("div", { className: "sc121-fig" }, /* @__PURE__ */ React.createElement(Money, { value: t.itcKept, size: "l", roll: true }), /* @__PURE__ */ React.createElement("span", { className: "sc121-what" }, "of input credit kept")), /* @__PURE__ */ React.createElement("p", { className: "sc121-working" }, "Sold under tax invoices, so the credit stands. ", /* @__PURE__ */ React.createElement("b", null, fmt.inr(t.itcReversed)), " reversed under s.17(5)(h) on packs destroyed or given away (GSTR-3B Table 4(B)(1)). ", t.invoices, " distributors' invoices, ", t.creditNotes, " credit notes, every pack reviewed."));
    return /* @__PURE__ */ React.createElement("div", { className: "sc121-head" }, /* @__PURE__ */ React.createElement("div", { className: "sc121-fig" }, /* @__PURE__ */ React.createElement(Kilos, { value: t.kg }), /* @__PURE__ */ React.createElement("span", { className: "sc121-what" }, "kept out of landfill")), /* @__PURE__ */ React.createElement("p", { className: "sc121-working" }, kg(t.resoldKg), " resold and ", kg(t.donatedKg), " donated, ", fmt.num(t.meals), " meals. ", /* @__PURE__ */ React.createElement("b", null, kg(t.destroyedKg)), " destroyed when it expired at the godown. ", kg(t.co2), " CO₂e avoided, indicative. ", p.long, "."));
  }
  const TABS = [{ id: "money", label: "Money", icon: "coins" }, { id: "papers", label: "Papers", icon: "file-text" }, { id: "impact", label: "Impact", icon: "leaf" }];
  const FIRST = { finance: "papers", sustainability: "impact" };
  const Row = ({ k, sub, v, tone, strong }) => /* @__PURE__ */ React.createElement("div", { className: cx("sc121-line", strong && "strong") }, /* @__PURE__ */ React.createElement("span", null, k, sub && /* @__PURE__ */ React.createElement("em", null, " ", sub)), /* @__PURE__ */ React.createElement("span", { className: cx("tnum", tone) }, v));
  function MoneyTab({ b }) {
    const s = b.sku, r = b.realised, wo = b.plan.writeOff, lines = r.lines.filter((l) => l.id !== "writeoff" && l.units > 0);
    const priceOf = (l) => l.id === "expiresoon" && b.price ? b.price : l.price;
    const rev = (l) => l.id === "expiresoon" && b.price ? r2(l.units * b.price) : l.gross;
    return /* @__PURE__ */ React.createElement(
      Columns,
      {
        sideWidth: 380,
        main: /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 16 } }, /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "What happened"), /* @__PURE__ */ React.createElement(OutcomeBadge, { o: b.outcome, size: "sm" })), lines.map((l) => /* @__PURE__ */ React.createElement(Row, { key: l.id, k: `${fmt.num(l.units)} → ${l.short}`, sub: l.id === "kirana" && b.kirana && b.kirana.ordered < b.kirana.planned ? `ordered of ${fmt.num(b.kirana.planned)} offered` : l.id === "foodbank" ? b.partner.name : `at ${fmt.rate ? fmt.rate(priceOf(l)) : "₹" + priceOf(l)}`, v: l.id === "foodbank" ? "given" : fmt.inr(rev(l)) })), /* @__PURE__ */ React.createElement(Row, { k: "Van, listing fee and handling", v: fmt.inr(-r.costs), tone: "neg" }), r.itcLoss ? /* @__PURE__ */ React.createElement(Row, { k: "Input credit given away with the donation", sub: "s.17(5)(h)", v: fmt.inr(-r.itcLoss), tone: "neg" }) : null, /* @__PURE__ */ React.createElement(Row, { k: "Recovered", v: fmt.inr(b.ledger.net), strong: true }), b.realised.godown ? /* @__PURE__ */ React.createElement("div", { className: "sc121-note" }, /* @__PURE__ */ React.createElement(Icon, { name: "warehouse", size: 16 }), /* @__PURE__ */ React.createElement("span", null, fmt.num(b.realised.godown), " packs no channel took expired at ", b.dist.godown, ". They came back to Munchly for full credit (", fmt.inr(b.expiry.credit), ") and Munchly destroyed them: disposal, EPR and ", inr2(b.expiry.itc), " of credit reversed.")) : null), /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "If it had been destroyed"), /* @__PURE__ */ React.createElement(Badge, { size: "sm", tone: "red", icon: "trash-2" }, "write-off")), /* @__PURE__ */ React.createElement(Row, { k: "Stock at cost", sub: `${fmt.num(wo.units)} × ₹${s.cost}`, v: fmt.inr(-wo.stock), tone: "neg" }), /* @__PURE__ */ React.createElement(Row, { k: "Input credit reversed", sub: `s.17(5)(h) · ₹${wo.itcPerUnit} a pack`, v: fmt.inr(-wo.itc), tone: "neg" }), /* @__PURE__ */ React.createElement(Row, { k: "Disposal and EPR", sub: "indicative", v: fmt.inr(-(wo.disposal + wo.epr)), tone: "neg" }), /* @__PURE__ */ React.createElement(Row, { k: "Effect on the P&L", v: fmt.inr(-wo.total), tone: "neg", strong: true }))),
        side: /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 16 } }, /* @__PURE__ */ React.createElement(Card, { className: "stack tight", style: { gap: 6 } }, /* @__PURE__ */ React.createElement("span", { className: "t-footnote subtle" }, "Better than destroying it"), /* @__PURE__ */ React.createElement(Money, { value: b.ledger.swing, size: "m", tone: "pos" }), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, "P&L ", fmt.inr(b.ledger.pnl), " instead of ", fmt.inr(-wo.total), ".")), /* @__PURE__ */ React.createElement(List, { head: "Munchly's side" }, /* @__PURE__ */ React.createElement(ListRow, { icon: "hand-coins", title: `Price support to ${b.dist.short}`, sub: b.numbers.support, value: fmt.inr(b.support.total) }), b.expiry ? /* @__PURE__ */ React.createElement(ListRow, { icon: "warehouse", title: "Expiry credit", sub: `${b.numbers.expiry} · ${fmt.num(b.expiry.units)} packs`, value: fmt.inr(b.expiry.credit) }) : null, b.award ? /* @__PURE__ */ React.createElement(ListRow, { icon: "receipt", title: `${b.dist.short}'s invoice to ${D.BUYER.short}`, sub: b.numbers.invoice, value: fmt.inr(b.docs.find((d) => d.id === "invoice").total) }) : null))
      }
    );
  }
  function PapersTab({ b }) {
    const [sel, setSel] = useState(null);
    const app = useApp();
    const r = b.realised, away = r.donated + r.destroyed;
    return /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 16 } }, /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "GST on this batch"), /* @__PURE__ */ React.createElement(Badge, { size: "sm", tone: "green", icon: "check" }, "reviewed · ", day(b.reviewed.on))), /* @__PURE__ */ React.createElement("div", { className: "sc121-gst" }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "t-footnote subtle" }, "Input credit kept"), /* @__PURE__ */ React.createElement(Money, { value: b.ledger.itcKept, size: "s", decimals: true }), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, fmt.num(r.soldUnits), " packs sold under tax invoices × ₹", b.sku.itcPerUnit)), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "t-footnote subtle" }, "Reversed, s.17(5)(h)"), /* @__PURE__ */ React.createElement(Money, { value: b.ledger.itcReversed, size: "s", decimals: true, tone: b.ledger.itcReversed ? "neg" : void 0 }), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, away ? `${fmt.num(away)} packs ${r.donated && r.destroyed ? "donated or destroyed" : r.donated ? "donated" : "destroyed"} · GSTR-3B Table 4(B)(1)` : "Nothing destroyed or given away")), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("span", { className: "t-footnote subtle" }, "Credit notes"), /* @__PURE__ */ React.createElement("span", { className: "num s" }, 1 + (b.expiry ? 1 : 0)), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, "financial, no GST adjustment")))), /* @__PURE__ */ React.createElement(SectionTitle, { sub: "Each paper generated, issued or not required, with its number" }, "Document pack"), /* @__PURE__ */ React.createElement("div", { className: "docgrid" }, b.docs.map((d) => /* @__PURE__ */ React.createElement(DocCard, { key: d.id, doc: d, onOpen: () => setSel(d.id) }))), /* @__PURE__ */ React.createElement(Sheet, { open: !!sel, onClose: () => setSel(null), title: sel ? b.docs.find((d) => d.id === sel).type : "" }, sel ? /* @__PURE__ */ React.createElement(PaperSummary, { d: b.docs.find((x) => x.id === sel), b }) : null));
  }
  function PaperSummary({ d, b }) {
    return /* @__PURE__ */ React.createElement("div", { className: "paper pp" }, /* @__PURE__ */ React.createElement("div", { className: "pp-head" }, /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { className: "pp-title" }, d.type), /* @__PURE__ */ React.createElement("div", { className: "pp-no" }, d.no, " · ", d.owner)), /* @__PURE__ */ React.createElement("span", { className: "pp-stamp ok" }, d.status)), d.id === "itc" ? /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(Row, { k: "Packs sold under tax invoices", v: fmt.num(b.realised.soldUnits) }), /* @__PURE__ */ React.createElement(Row, { k: "Packs donated or destroyed", v: fmt.num(b.realised.donated + b.realised.destroyed) }), /* @__PURE__ */ React.createElement(Row, { k: "Input credit kept", v: inr2(d.amount), strong: true }), /* @__PURE__ */ React.createElement(Row, { k: "Reversed in GSTR-3B, Table 4(B)(1)", v: inr2(d.reversed || 0) })) : d.amount ? /* @__PURE__ */ React.createElement(Row, { k: "Amount", v: inr2(d.amount), strong: true }) : /* @__PURE__ */ React.createElement("p", { className: "pp-note" }, d.note || "Nothing to file."));
  }
  function ImpactTab({ b }) {
    const L = b.ledger;
    const ev = [b.numbers.invoice, b.numbers.listing, b.kirana ? `${fmt.num(b.kirana.ordered)} packets of kirana orders` : null, b.numbers.support, b.numbers.expiry, b.numbers.receipt, L.donated ? "FSSAI checklist" : null, b.realised.destroyed ? "destruction certificate" : null].filter(Boolean);
    return /* @__PURE__ */ React.createElement(
      Columns,
      {
        sideWidth: 380,
        main: /* @__PURE__ */ React.createElement("div", { className: "stack", style: { gap: 16 } }, /* @__PURE__ */ React.createElement(Card, { className: "stack snug" }, /* @__PURE__ */ React.createElement("div", { className: "card-head" }, /* @__PURE__ */ React.createElement("span", { className: "card-title" }, "BRSR line"), /* @__PURE__ */ React.createElement(Badge, { size: "sm", tone: "green", icon: "check" }, "posted · ", day(b.cleared))), /* @__PURE__ */ React.createElement("div", { className: "sc121-brsr mono" }, kg(L.kg), " diverted from disposal (", kg(L.resoldKg), " resold", L.donatedKg ? `, ${kg(L.donatedKg)} donated` : "", ") · ", kg(L.destroyedKg), " destroyed · ", kg(L.co2), " CO₂e avoided (indicative) · ", L.meals ? `${fmt.num(L.meals)} meals` : "0 meals (nothing donated)"), /* @__PURE__ */ React.createElement("span", { className: "t-footnote subtle" }, "Evidence: ", ev.join(" · "))), /* @__PURE__ */ React.createElement(List, { head: "Where the kilos went" }, /* @__PURE__ */ React.createElement(ListRow, { icon: "store", title: "Resold", sub: "kiranas, ExpireSoon and staff", value: kg(L.resoldKg) }), /* @__PURE__ */ React.createElement(ListRow, { icon: "heart-handshake", title: "Donated", sub: b.partner ? b.partner.name : "nothing donated", value: kg(L.donatedKg) }), /* @__PURE__ */ React.createElement(ListRow, { icon: "trash-2", title: "Destroyed", sub: L.destroyedKg ? "expired at the godown" : "nothing destroyed", value: kg(L.destroyedKg) }))),
        side: /* @__PURE__ */ React.createElement(Card, { className: "stack tight", style: { gap: 6 } }, /* @__PURE__ */ React.createElement("span", { className: "t-footnote subtle" }, "Kept out of landfill"), /* @__PURE__ */ React.createElement("span", { className: "num m" }, kg(L.kg)), /* @__PURE__ */ React.createElement("span", { className: "t-footnote muted" }, kg(L.co2), " CO₂e avoided at ", M.RULES.co2PerKg, " kg a kg, indicative", L.meals ? ` · ${fmt.num(L.meals)} meals by ${b.partner.name}'s rule` : "", "."))
      }
    );
  }
  function BatchPage({ me, b, back, onBack }) {
    const app = useApp();
    const phone = app.bp === "phone";
    const [tab, setTab] = useState(FIRST[me.role] || "money");
    const head = /* @__PURE__ */ React.createElement("div", { className: "bhead" }, /* @__PURE__ */ React.createElement("div", { className: "bh-id" }, /* @__PURE__ */ React.createElement("span", { className: "bh-pic", "aria-hidden": "true" }, /* @__PURE__ */ React.createElement(Product, { name: b.sku.img, size: phone ? 46 : 72 })), /* @__PURE__ */ React.createElement("div", { className: "bh-tt" }, /* @__PURE__ */ React.createElement("h1", null, b.sku.name), /* @__PURE__ */ React.createElement("div", { className: "bh-meta" }, /* @__PURE__ */ React.createElement("span", { className: "mono" }, b.ref), /* @__PURE__ */ React.createElement("span", { className: "sep", "aria-hidden": "true" }, "·"), /* @__PURE__ */ React.createElement("span", null, b.dist.name, ", ", b.dist.city)), /* @__PURE__ */ React.createElement("div", { className: "bh-meta" }, /* @__PURE__ */ React.createElement(OutcomeBadge, { o: b.outcome }), /* @__PURE__ */ React.createElement("span", null, "Flagged ", day(b.flagged), " · cleared ", day(b.cleared))))), /* @__PURE__ */ React.createElement("nav", { className: "bh-tabs", "aria-label": `${b.sku.name}, ${b.ref}` }, TABS.map((t) => /* @__PURE__ */ React.createElement("button", { key: t.id, type: "button", className: "bh-tab", "aria-current": tab === t.id ? "page" : void 0, onClick: () => setTab(t.id) }, tab === t.id && /* @__PURE__ */ React.createElement(motion.span, { layoutId: "sc121-tab", className: "bh-tab-thumb", transition: { type: "spring", stiffness: 500, damping: 40 } }), !phone && /* @__PURE__ */ React.createElement(Icon, { name: t.icon, size: 16 }), /* @__PURE__ */ React.createElement("span", null, t.label)))));
    return /* @__PURE__ */ React.createElement(Screen, { me, title: b.sku.name, back, hideLarge: true, below: head }, /* @__PURE__ */ React.createElement(AnimatePresence, { mode: "wait" }, /* @__PURE__ */ React.createElement(motion.div, { key: tab, initial: { opacity: 0, y: 6 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0 }, transition: { duration: 0.22, ease: [0.22, 1, 0.36, 1] } }, tab === "money" ? /* @__PURE__ */ React.createElement(MoneyTab, { b }) : tab === "papers" ? /* @__PURE__ */ React.createElement(PapersTab, { b }) : /* @__PURE__ */ React.createElement(ImpactTab, { b }))));
  }
  function useBatchOf() {
    const { route } = useRoute();
    const ref = route && route.params && route.params.ref;
    return ref ? X.batches.find((b) => b.ref === ref) || null : null;
  }
  window.SC121K = { OutcomeBadge, PeriodSwitch, ReadingSwitch, READINGS, valueOf, Headline, Lakh, Kilos, BatchPage, useBatchOf, day, month, kg, inr2 };
})();
