<script lang="ts">
	import Icon from '../icons/Icon.svelte';
	import type { IconName } from '../icons/registry';
	import type { Doc } from '../workspace/types';
	import Badge from './Badge.svelte';
	import Money from './Money.svelte';

	// a document in the pack: generated by Munchly, drafted for the distributor to issue, or not required (the kit's
	// DocCard)
	type Props = { doc: Doc; onopen?: () => void };
	let { doc, onopen }: Props = $props();
	const ready = $derived(doc.status === 'generated' || doc.status === 'drafted');
	const ICON: Record<string, IconName> = {
		invoice: 'receipt',
		eway: 'truck',
		support: 'hand-coins',
		itc: 'badge-check',
		fssai: 'clipboard-check'
	};
	const icon = $derived(ICON[doc.id] || 'file-check');
</script>

<button
	type="button"
	class="card interactive"
	onclick={onopen}
	style="padding: 18px; text-align: left; display: grid; gap: 10px"
>
	<div class="row between">
		<span class={ready ? 'icontile' : 'icontile soft'}><Icon name={icon} size={17} stroke={2} /></span><Badge
			size="sm"
			tone={doc.status === 'generated' ? 'green' : doc.status === 'awaiting' ? 'amber' : undefined}>{doc.status}</Badge
		>
	</div>
	<div>
		<div class="strong">{doc.type}</div>
		<div class="mono subtle t-caption">{doc.no}{doc.owner ? ' · ' + doc.owner : ''}</div>
	</div>
	{#if doc.amount}<Money value={doc.amount} size="s" />{:else}<span class="t-footnote muted"
			>{doc.note || (ready ? 'Attached' : 'Nothing to file')}</span
		>{/if}
</button>
