"""baseline: reference data, people, clients, activity, audit log

Every object belongs to sc_owner (env.py sets the role). sc_app, the API's role, may read and write the data, only
read the reference data (loaded at migrate time), and only insert into and read the audit log, which triggers also
keep append-only for its owner.

Revision ID: 0001
Revises:
Create Date: 2026-10-06 11:53:24.301177
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

REFERENCE = ("plans", "agents", "connectors", "exits", "roles", "permissions", "role_permissions", "documents")
GRANTS = [
    "GRANT USAGE ON SCHEMA sc TO sc_app",
    "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sc TO sc_app",
    "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA sc TO sc_app",
    # the reference data is the platform's definition: loaded by migrations, read by the API
    f"REVOKE INSERT, UPDATE, DELETE ON {', '.join('sc.' + t for t in REFERENCE)} FROM sc_app",
    "REVOKE ALL ON sc.alembic_version FROM sc_app",
    # the audit log: append and read, nothing else
    "REVOKE UPDATE, DELETE, TRUNCATE ON sc.audit_log FROM sc_app",
    """
    CREATE FUNCTION sc.audit_log_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION 'the audit log is append-only: % refused', TG_OP USING ERRCODE = 'insufficient_privilege';
    END
    $$
    """,
    """
    CREATE TRIGGER audit_log_no_update_or_delete BEFORE UPDATE OR DELETE ON sc.audit_log
      FOR EACH ROW EXECUTE FUNCTION sc.audit_log_append_only()
    """,
    """
    CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON sc.audit_log
      FOR EACH STATEMENT EXECUTE FUNCTION sc.audit_log_append_only()
    """,
    # tables later migrations add get the same privileges
    "ALTER DEFAULT PRIVILEGES FOR ROLE sc_owner IN SCHEMA sc GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sc_app",
    "ALTER DEFAULT PRIVILEGES FOR ROLE sc_owner IN SCHEMA sc GRANT USAGE, SELECT ON SEQUENCES TO sc_app",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("job", sa.Text(), nullable=False),
        sa.Column("is_gate", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        schema="sc",
    )
    op.create_table(
        "connectors",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectors")),
        schema="sc",
    )
    op.create_table(
        "documents",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_documents")),
        schema="sc",
    )
    op.create_table(
        "exits",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exits")),
        schema="sc",
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        schema="sc",
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        schema="sc",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("team", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("scope", "name", name=op.f("uq_roles_scope_name")),
        schema="sc",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("firebase_uid", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone_e164", sa.Text(), nullable=True),
        sa.Column("password_state", sa.Text(), server_default="none", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_sign_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("password_state in ('default','own','none')", name=op.f("ck_users_password_state")),
        sa.CheckConstraint("phone_e164 ~ '^\\+[0-9]{8,15}$'", name=op.f("ck_users_phone_e164")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lower")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("firebase_uid", name=op.f("uq_users_firebase_uid")),
        sa.UniqueConstraint("phone_e164", name=op.f("uq_users_phone_e164")),
        schema="sc",
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short", sa.Text(), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("industry", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("email_domain", sa.Text(), nullable=False),
        sa.Column("mark", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plan_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("live_since", sa.Date(), nullable=True),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("route", sa.Text(), nullable=False),
        sa.Column("owner", sa.Text(), nullable=False),
        sa.Column("expiry", sa.Text(), nullable=False),
        sa.Column("gate_blinkit_days", sa.Integer(), nullable=False),
        sa.Column("gate_qcom_pct", sa.Integer(), nullable=False),
        sa.Column("return_window_days", sa.Integer(), nullable=False),
        sa.Column("territory_guard", sa.Boolean(), nullable=False),
        sa.Column("approver_ref", sa.Text(), nullable=True),
        sa.Column("staff_cap", sa.Integer(), nullable=False),
        sa.Column("offer_window_hours", sa.Integer(), nullable=False),
        sa.Column("hindi_offers", sa.Boolean(), nullable=False),
        sa.Column("require_photo", sa.Boolean(), nullable=False),
        sa.Column("sign_in", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.CheckConstraint("expiry in ('full-credit','price-support','none')", name=op.f("ck_clients_expiry")),
        sa.CheckConstraint("owner in ('distributor','manufacturer')", name=op.f("ck_clients_owner")),
        sa.CheckConstraint("route in ('distributors','modern-trade','own')", name=op.f("ck_clients_route")),
        sa.CheckConstraint("status in ('setting-up','live')", name=op.f("ck_clients_status")),
        sa.CheckConstraint("email_domain = lower(email_domain)", name=op.f("ck_clients_email_domain_lower")),
        sa.CheckConstraint("gate_blinkit_days between 30 and 180", name=op.f("ck_clients_gate_blinkit_days")),
        sa.CheckConstraint("gate_qcom_pct between 30 and 90", name=op.f("ck_clients_gate_qcom_pct")),
        sa.CheckConstraint("offer_window_hours between 1 and 168", name=op.f("ck_clients_offer_window_hours")),
        sa.CheckConstraint("return_window_days between 7 and 45", name=op.f("ck_clients_return_window_days")),
        sa.CheckConstraint("staff_cap between 0 and 1000", name=op.f("ck_clients_staff_cap")),
        sa.ForeignKeyConstraint(["plan_id"], ["sc.plans.id"], name=op.f("fk_clients_plan_id_plans")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("domain", name=op.f("uq_clients_domain")),
        sa.UniqueConstraint("seq", name=op.f("uq_clients_seq")),
        schema="sc",
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Text(), nullable=False),
        sa.Column("permission_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["sc.permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["sc.roles.id"], name=op.f("fk_role_permissions_role_id_roles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
        schema="sc",
    )
    op.create_table(
        "staff_members",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ref", sa.Text(), nullable=False),
        sa.Column("role_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short", sa.Text(), nullable=False),
        sa.Column("team", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.ForeignKeyConstraint(["invited_by"], ["sc.users.id"], name=op.f("fk_staff_members_invited_by_users")),
        sa.ForeignKeyConstraint(["role_id"], ["sc.roles.id"], name=op.f("fk_staff_members_role_id_roles")),
        sa.ForeignKeyConstraint(["user_id"], ["sc.users.id"], name=op.f("fk_staff_members_user_id_users")),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_staff_members")),
        sa.UniqueConstraint("ref", name=op.f("uq_staff_members_ref")),
        sa.UniqueConstraint("seq", name=op.f("uq_staff_members_seq")),
        schema="sc",
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("ran_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["sc.agents.id"], name=op.f("fk_agent_runs_agent_id_agents")),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_agent_runs_client_id_clients")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        schema="sc",
    )
    op.create_index(op.f("ix_agent_runs_ran_at"), "agent_runs", ["ran_at"], unique=False, schema="sc")
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_name", sa.Text(), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["sc.users.id"], name=op.f("fk_audit_log_actor_user_id_users")),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_audit_log_client_id_clients")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        schema="sc",
    )
    op.create_index(op.f("ix_audit_log_client_id_id"), "audit_log", ["client_id", "id"], unique=False, schema="sc")
    op.create_table(
        "client_agents",
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.Text(), nullable=False),
        sa.Column("on", sa.Boolean(), nullable=False),
        sa.Column("autonomy", sa.Text(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_note", sa.Text(), nullable=True),
        sa.Column("next_note", sa.Text(), nullable=True),
        sa.CheckConstraint("autonomy in ('suggest','ask','act','gate')", name=op.f("ck_client_agents_autonomy")),
        sa.ForeignKeyConstraint(["agent_id"], ["sc.agents.id"], name=op.f("fk_client_agents_agent_id_agents")),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_client_agents_client_id_clients")),
        sa.PrimaryKeyConstraint("client_id", "agent_id", name=op.f("pk_client_agents")),
        schema="sc",
    )
    op.create_table(
        "client_exits",
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("exit_id", sa.Text(), nullable=False),
        sa.Column("on", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_client_exits_client_id_clients")),
        sa.ForeignKeyConstraint(["exit_id"], ["sc.exits.id"], name=op.f("fk_client_exits_exit_id_exits")),
        sa.PrimaryKeyConstraint("client_id", "exit_id", name=op.f("pk_client_exits")),
        schema="sc",
    )
    op.create_table(
        "client_integrations",
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.CheckConstraint("status in ('ok','mock','soon','waiting')", name=op.f("ck_client_integrations_status")),
        sa.ForeignKeyConstraint(
            ["client_id"], ["sc.clients.id"], name=op.f("fk_client_integrations_client_id_clients")
        ),
        sa.PrimaryKeyConstraint("client_id", "id", name=op.f("pk_client_integrations")),
        sa.UniqueConstraint("seq", name=op.f("uq_client_integrations_seq")),
        schema="sc",
    )
    op.create_table(
        "client_members",
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("ref", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("org", sa.Text(), nullable=False),
        sa.Column("role_label", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("access_role_id", sa.Text(), nullable=False),
        sa.Column("workspace_role", sa.Text(), nullable=True),
        sa.Column("member_class", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("img", sa.Text(), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.CheckConstraint(
            "member_class in ('staff','partner','external')", name=op.f("ck_client_members_member_class")
        ),
        sa.CheckConstraint("status in ('invited','active','deactivated')", name=op.f("ck_client_members_status")),
        sa.ForeignKeyConstraint(
            ["access_role_id"], ["sc.roles.id"], name=op.f("fk_client_members_access_role_id_roles")
        ),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_client_members_client_id_clients")),
        sa.ForeignKeyConstraint(["user_id"], ["sc.users.id"], name=op.f("fk_client_members_user_id_users")),
        sa.PrimaryKeyConstraint("client_id", "ref", name=op.f("pk_client_members")),
        sa.UniqueConstraint("client_id", "user_id", name=op.f("uq_client_members_client_id_user_id")),
        sa.UniqueConstraint("seq", name=op.f("uq_client_members_seq")),
        schema="sc",
    )
    op.create_table(
        "demo_requests",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("makes", sa.Text(), nullable=False),
        sa.Column("plan", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=True),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.CheckConstraint("status in ('new','set up')", name=op.f("ck_demo_requests_status")),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_demo_requests_client_id_clients")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demo_requests")),
        sa.UniqueConstraint("seq", name=op.f("uq_demo_requests_seq")),
        schema="sc",
    )
    op.create_table(
        "distributors",
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("kiranas", sa.Integer(), nullable=False),
        sa.Column("staff_cap", sa.Integer(), nullable=True),
        sa.Column("permission", sa.Text(), nullable=False),
        sa.Column("permission_given_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("export_expected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("export_arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.CheckConstraint("permission in ('given','not-yet')", name=op.f("ck_distributors_permission")),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_distributors_client_id_clients")),
        sa.PrimaryKeyConstraint("client_id", "id", name=op.f("pk_distributors")),
        sa.UniqueConstraint("seq", name=op.f("uq_distributors_seq")),
        schema="sc",
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_invitations_client_id_clients")),
        sa.ForeignKeyConstraint(["created_by"], ["sc.users.id"], name=op.f("fk_invitations_created_by_users")),
        sa.ForeignKeyConstraint(["user_id"], ["sc.users.id"], name=op.f("fk_invitations_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        schema="sc",
    )
    op.create_table(
        "skus",
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mrp", sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
        sa.Column("gst", sa.Numeric(precision=5, scale=4, asdecimal=False), nullable=False),
        sa.Column("life_days", sa.Integer(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.CheckConstraint("gst >= 0 and gst < 1", name=op.f("ck_skus_gst")),
        sa.CheckConstraint("life_days > 0", name=op.f("ck_skus_life_days")),
        sa.CheckConstraint("mrp > 0", name=op.f("ck_skus_mrp")),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_skus_client_id_clients")),
        sa.PrimaryKeyConstraint("client_id", "id", name=op.f("pk_skus")),
        sa.UniqueConstraint("seq", name=op.f("uq_skus_seq")),
        schema="sc",
    )
    op.create_table(
        "batches",
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("ref", sa.Text(), nullable=False),
        sa.Column("sku_id", sa.Text(), nullable=False),
        sa.Column("distributor_id", sa.Text(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("stage_done", sa.Integer(), nullable=False),
        sa.Column("stage_current", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("money", sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
        sa.Column("split", sa.Text(), nullable=True),
        sa.Column("recovered", sa.Numeric(precision=12, scale=2, asdecimal=False), server_default="0", nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.CheckConstraint(
            "stage_done between 0 and 9 and stage_current between 0 and 9", name=op.f("ck_batches_stages")
        ),
        sa.ForeignKeyConstraint(
            ["client_id", "distributor_id"],
            ["sc.distributors.client_id", "sc.distributors.id"],
            name=op.f("fk_batches_client_id_distributor_id_distributors"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id", "sku_id"], ["sc.skus.client_id", "sc.skus.id"], name=op.f("fk_batches_client_id_sku_id_skus")
        ),
        sa.ForeignKeyConstraint(["client_id"], ["sc.clients.id"], name=op.f("fk_batches_client_id_clients")),
        sa.PrimaryKeyConstraint("client_id", "ref", name=op.f("pk_batches")),
        sa.UniqueConstraint("seq", name=op.f("uq_batches_seq")),
        schema="sc",
    )
    op.create_foreign_key(
        "fk_clients_approver",
        "clients",
        "client_members",
        ["id", "approver_ref"],
        ["client_id", "ref"],
        source_schema="sc",
        referent_schema="sc",
        deferrable=True,
        initially="DEFERRED",
    )
    # ### end Alembic commands ###

    for statement in GRANTS:
        op.execute(statement)


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS sc.audit_log_append_only() CASCADE")
    op.drop_constraint("fk_clients_approver", "clients", schema="sc", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("batches", schema="sc")
    op.drop_table("skus", schema="sc")
    op.drop_table("invitations", schema="sc")
    op.drop_table("distributors", schema="sc")
    op.drop_table("demo_requests", schema="sc")
    op.drop_table("client_members", schema="sc")
    op.drop_table("client_integrations", schema="sc")
    op.drop_table("client_exits", schema="sc")
    op.drop_table("client_agents", schema="sc")
    op.drop_index(op.f("ix_audit_log_client_id_id"), table_name="audit_log", schema="sc")
    op.drop_table("audit_log", schema="sc")
    op.drop_index(op.f("ix_agent_runs_ran_at"), table_name="agent_runs", schema="sc")
    op.drop_table("agent_runs", schema="sc")
    op.drop_table("staff_members", schema="sc")
    op.drop_table("role_permissions", schema="sc")
    op.drop_table("clients", schema="sc")
    op.drop_table("users", schema="sc")
    op.drop_table("roles", schema="sc")
    op.drop_table("plans", schema="sc")
    op.drop_table("permissions", schema="sc")
    op.drop_table("exits", schema="sc")
    op.drop_table("documents", schema="sc")
    op.drop_table("connectors", schema="sc")
    op.drop_table("agents", schema="sc")
    # ### end Alembic commands ###
